### ISSUE TITLE
[FEATURE REQUEST] Add Option to export as normal text

### ISSUE THREAD

**Issue by Aaron2550** [Flameish/Novel-Grabber#104]
**Is your feature request related to a problem? Please describe.**
When training a RecurrentNeuralNetwork on WebNovels, it's kind of annoying to convert the .epub files back to text.

**Describe the solution you'd like**
Add an option in the GUI or the CLI to allow for .txt output

**Describe alternatives you've considered**
Converting the .epub files using an online converter

**Additional context**
idk

**Comment by Flameish** [comment]
Added

**Comment by Aaron2550** [comment]
Thanks! I'll close this then
