### ISSUE TITLE
[FEATURE REQUEST] login for dreame and booknet

### ISSUE THREAD

**Issue by soujanyabukka** [Flameish/Novel-Grabber#106]
Can u please upgrade the use accounts login for dreame website and booknet.com. Because i cannot download.

**Comment by Flameish** [comment]
I will be reworking login completely today / this weekend.

**Comment by soujanyabukka** [comment]
> I will be reworking the login system completely today / this weekend.

Thank u😄

**Comment by soujanyabukka** [comment]
Thank you😄

**Comment by Flameish** [comment]
Try out the new version and see if it works better.

**Comment by soujanyabukka** [comment]
Thank you😄👍
