### ISSUE TITLE
[BUG] login issues in sources

### ISSUE THREAD

**Issue by soujanyabukka** [Flameish/Novel-Grabber#108]
I cant login into my booknet and dreame account after get cookies. Can u please explain me in detail how to login after get cookies.  After logging in my browser it is not downloading in automatic
![16132950574574308111699373370316](https://user-images.githubusercontent.com/31979580/107873091-9f9eb580-6ed5-11eb-8108-cc41dd60989e.jpg)

**Comment by Flameish** [comment]
When you click Get Cookies, a Browaer window should open. Login like you normally would and close the window. You should see a bunch of cookies if you click on Edit Cookies to make sure. 

Now on automatic you should just need to select Use account before checking.

**Comment by soujanyabukka** [comment]
I have logged in but the chapter container is not found and it could not connect for booknet.com.
![IMG_20210215_113700](https://user-images.githubusercontent.com/31979580/107979979-7b31fe80-6fe5-11eb-9532-6e886f0d38ca.jpg)

**Comment by Flameish** [comment]
Should be fixed now.

**Comment by xx255q** [comment]
When I attempt to sign in with a cookie the program just locks up

**Comment by soujanyabukka** [comment]
> Booknet should be fixed now. Do you also have a problem with Dreame?

Yeah dreame login also not working

**Comment by Flameish** [comment]
Another person reported a problem where the login cookies were not working for webnovel.com but which was fixed with a relog, so maybe try doing that. I can't actually test Dreame since I can't create an account but it should work.

I've also added a button, which shows after starting the browser, to save the cookies.

**Comment by soujanyabukka** [comment]
Thank you 😄👍 Ut is working
