### ISSUE TITLE
Webnovel Can't Download Unlocked Chapters

### ISSUE THREAD

**Issue by JDcarmelo** [Flameish/Novel-Grabber#11]
i can't download unlocked chapters in webnovel (not the privilage the normal locked chapters). I can only grab the Free chapters so the epub won't really update

**Comment by Flameish** [comment]
Novel-Grabber can't download locked (paid chapters) and probably won't be able to in the future aswell.
I'm not sure what privileged chapters are in comparison, and you give me an example?

**Comment by JDcarmelo** [comment]
Well i was just wondering how "wuxiaworld.co" can get locked chapters from qidian.
And privilege are advanced chapters that author stacked and you have to pay a corresponding amount of SS per month to read it
![Screenshot_20191114-081053_Webnovel](https://user-images.githubusercontent.com/57732601/68815480-84cc0880-06b6-11ea-89f5-d6feb53bbccb.jpg)
