### ISSUE TITLE
[SITE REQUEST] https://www.asianovel.net/

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#110]
Can I request for https://www.asianovel.net/ to be added, please? Only chapters from a specific page could be extracted by manual grabbing. To be able to get all chapters, I needed to grab chapters from every page manually. Thank you very much!

**Comment by Flameish** [comment]
Added. Not sure why covers are not showing up sometimes.

**Comment by JasCU100** [comment]
Thank you very much!
