### ISSUE TITLE
Site Request fictionpress

### ISSUE THREAD

**Issue by zpereyra** [Flameish/Novel-Grabber#111]
Fictionpress
**Does the host have more than 15 novels?**

Yes

**Did you try manual grabbing?**

No
**Website link:**

https://www.fictionpress.com/

Thank you.

**Comment by Flameish** [comment]
Fictionpress, Fanfiction.net and Fanfiktion.de are not possible to scrape with NG right now. I might take a look to see if something changed recently, but I don't think so.
