### ISSUE TITLE
[BUG] Slow downloads

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#114]
Lately, I noticed that the crawling of chapters in NovelUpdates and CG is very slow, whereas before it was faster. There are also often errors like "Could not connect to webpage." It is in contrast with chapters from SkyNovel, which is very fast. Thank you!

**Comment by Flameish** [comment]
The download speed is only limited by your internet connection and most importantly the server you're trying to fetch from. To not overload the host server I strongly suggest to use a wait time of multiple seconds anyway.

Another thing concerning NovelUpdates is that they do not host any novels or chapters themself. NG will just fetch metadata from NovelUpdates and then follow the chapter links to the server the novel is actually hosted on.
