### ISSUE TITLE
Tutorial on how to add the bot to telegram

### ISSUE THREAD

**Issue by PleaseReadMe** [Flameish/Novel-Grabber#119]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
Uhmm I want to learn how to add the bot on telegram.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Flameish** [comment]
Check out the bot section on the Readme.  [Link](https://github.com/Flameish/Novel-Grabber/blob/master/README.md#how-to-use)
