### ISSUE TITLE
[BUG] ONLY ONE DOWNLOAD AT A TIME ALLOWED

### ISSUE THREAD

**Issue by PleaseReadMe** [Flameish/Novel-Grabber#121]
**Describe the bug**
 it keeps saying only one download a time allowed even though there is no novel downloading

**Steps to reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Platform**

**Logs**

**Additional context**

**Comment by PleaseReadMe** [comment]
![Uploading Screenshot_2021-03-07-20-51-02-26.jpg…]()

**Comment by PleaseReadMe** [comment]
![Screenshot_2021-03-07-20-51-02-26](https://user-images.githubusercontent.com/70464689/110240472-ff452980-7f86-11eb-91de-fc9880c623c3.jpg)

**Comment by PleaseReadMe** [comment]
Is the repository web scrapping or API?

**Comment by PleaseReadMe** [comment]
It's already fix

**Comment by Flameish** [comment]
Yeah after I started the bot today a lot of request, which stacked up over the night, overloaded the system/ allocated threads. It threw all kinds of errors.

Which repository do you mean? Novel-Grabber itself or the Telegram bot?

**Comment by PleaseReadMe** [comment]
The Novel-Grabber and the Telegram bot.

**Comment by Flameish** [comment]
Well you can look inside the source files. For hosts its basically just web scraping and "API" usage where available. The Telegram bot is build using a Telegram API java library hooked into NG.
