### ISSUE TITLE
[FEATURE REQUEST] docker container

### ISSUE THREAD

**Issue by kinderoth** [Flameish/Novel-Grabber#123]
Is it possible for this to have the ability to be deployed as a docker container. I run a headless server, and it would be awesome if I could run it via docker.

**Is your feature request related to a problem? Please describe.**
No

**Additional context**
I don't have experience in making containers, but have a container that will start the program, and give it web access that will display the gui?

**Comment by Flameish** [comment]
No idea about containers / docker. Its a java program, you can probably find your answer on google. But you can use it in a headless environment via CLI parameter or setting up a Telegram Bot.
