### ISSUE TITLE
[BUG] NU Error

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#124]
Just this day, I often get this error when I download from NovelUpdates: [ERROR]Service Unavailable! (503). I hope it would be resolved soon. Thank you!

**Comment by Flameish** [comment]
[A list of HTTP error codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_server_errors) 

Only thing you can do for a 503 is wait and ease up on requests
