### ISSUE TITLE
es.mtlnovel

### ISSUE THREAD

**Issue by LuHitomi** [Flameish/Novel-Grabber#126]
es.mtlnovel

Does the host have more than 15 novels?
Yes.

Did you try manual grabbing?
No.

https://es.mtlnovel.com

I cannot download novels in Spanish or any other language except for English from MTL. Please help. I only get "Host not supported: es.mtlnovel.com"

PS: I use the Telegram bot.

**Comment by Flameish** [comment]
Added all language variants of MTLNovel
