### ISSUE TITLE
How to use /cli command on Telegram?

### ISSUE THREAD

**Issue by PleaseReadMe** [Flameish/Novel-Grabber#130]
There is no bug I just don't know how to use the /cli command the instruction is kinda confusing. Can you show me a more examples on how to use it?

**Comment by Flameish** [comment]
These are the other options possible on the bot:

| Parameter | Arguments | Description |
| :--- | :---: | :---|
-link | {novel_URL} | URL to the novel's table of contents page. Starts download.
[-chapters] | {all}, {5 27}, {12 last}	| Specify which chapters to download.
[-noDesc] | | Don't create a description page.
[-removeStyle] | | Remove all styling from chapter body.
[-getImages] | | Grab images from chapter body as well.
[-displayTitle]| | Write the chapter title at the top of each chapter text.
[-invertOrder] | | Invert the chapter order.

If you don't specify the chapters option it will default to all.

Examples: (-link needs to come first)

`-link https://www.royalroad.com/fiction/22518/chrysalis -getImages`
Is equivalent to just sending the link: `https://www.royalroad.com/fiction/22518/chrysalis`

`-link https://www.royalroad.com/fiction/22518/chrysalis -getImages -chapters 10 15`
Download chapters 10 to 15 and get images.

`-link https://www.royalroad.com/fiction/22518/chrysalis -displayTitle -chapters 102 last -getImages`
Download chapters from 102 to the lastest, get images and add the chapter titles as headers on top of each chapter.

**Comment by PleaseReadMe** [comment]
Thank you!
