### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by JudahGoldstein** [Flameish/Novel-Grabber#131]
Heyo! Starting work on an open source LN/WN reader for android and would love to use this as part of my backend, what are you guys doing licensing wise? Wouldn't want to use someone's code for my own project without everything being proper. I see you have it listed as MIT but if you guys have personal credits and stuff you'd like included (or just don't want it used) I'll respect that.

**Comment by Flameish** [comment]
Nah just the MIT license with a link is fine. Keep the used libraries mind through.

**Comment by JudahGoldstein** [comment]
Great! and I definitely will.
