### ISSUE TITLE
[SITE REQUEST] reddit.com/r/hfy

### ISSUE THREAD

**Issue by AlleM43** [Flameish/Novel-Grabber#133]
**Does the host have more than 15 novels?**

Yes

**Did you try manual grabbing?**

Yes

**Website link:**

[reddit.com/r/hfy](https://www.reddit.com/r/hfy/)

**Other comments:**
This suggestion is specifically for the HFY subreddit, as they have a system of wiki pages for series on there that can be used as a TOC. Manual grabbing works with some link trimming (as the wiki pages are not "supported"), but has a bit of a problem with NSFW-marked chapters.

**Comment by Flameish** [comment]
There is no clean way to add just certain parts of websites as supported hosts. Reddit is just not a good source to be "fully" added but manual grabbing exists for exactly these cases. Ill see what I can do about adding cookie support to manual.
