### ISSUE TITLE
[BUG] Internal filenames are incremented if checking more than one book

### ISSUE THREAD

**Issue by C0rn3j** [Flameish/Novel-Grabber#136]
Novel Grabber 3.6.2

![image](https://user-images.githubusercontent.com/1641362/112138037-524aed80-8bd1-11eb-8f20-bff87ddfc285.png)
I think the counter is not reset, and every time the "Check availability of novel" button is pressed, its chapter count is added to the counter, thus mangling the filenames inside upon scraping.

This is not something a normal user notices but I need to work with the internal files with the proper names in this case.

Tested against multiple titles from webnovel.com with full chapter range:

![image](https://user-images.githubusercontent.com/1641362/112138294-a655d200-8bd1-11eb-9cbc-eed53160d55e.png)

Restarting Novel Grabber between each scrape works around the issue.

**Comment by Flameish** [comment]
Should be fixed for automatic grabbing. Take take through, it's not really thread safe. Meaning, if you try to check on automatic and on manual simultaneously, the numbers might not line up.
