### ISSUE TITLE
[SITE REQUEST] Piaotian

### ISSUE THREAD

**Issue by apaxc** [Flameish/Novel-Grabber#137]
**Does the host have more than 15 novels?**

Yes

**Did you try manual grabbing?**

Yes, and it works great.

**Website link:**

https://www.ptwxz.com/
https://www.piaotian.com/

**Comment by TehGodofDoooom** [comment]
Requesting Site Zetro Translation

https://zetrotranslation.com/

manual grabbing didn't work for me, although any explanation on how to properly use it(especially the CSS selector thing) would be appreciated

**Comment by Flameish** [comment]
@TehGodofDoooom please each site request in a new issue. Makes for a better overview.

You can take a look at [this](https://github.com/Flameish/Novel-Grabber/issues/62#issuecomment-730305855) for a more in depth explanation for how to use the css selector.

**Comment by Flameish** [comment]
Piaotian added. That site is so broken that I have to use the Find Chapter function from manual grabbing to even get something. So expect some errors.
