### ISSUE TITLE
[BUG] Chinese and other foreign characters are not being displayed

### ISSUE THREAD

**Issue by apaxc** [Flameish/Novel-Grabber#138]
**Is your feature request related to a problem? Please describe.**

When downloading novels that have Chinese or other foreign characters, these appear as black boxes.

**Describe the solution you'd like**

Support for Chinese and other foreign languages

**Describe alternatives you've considered**

I believe that this is the only thing that could be done.

**Additional context**

![特拉福买家俱乐部](https://user-images.githubusercontent.com/64091461/112144936-677c4800-8be2-11eb-97e2-50dfc26fce41.png)
![chinese](https://user-images.githubusercontent.com/64091461/112144938-6814de80-8be2-11eb-87ce-cfb86430910f.png)

**Comment by Flameish** [comment]
You can try setting the encoding when starting the jar as a workaround on windows for now.

`java -Dfile.encoding=utf-8 -jar Novel-Grabber.jar`

**Comment by Flameish** [comment]
It was a font problem. The font I used didn't have a good unicode character support on Windows / wrong fall back font. Please try again.

**Comment by apaxc** [comment]
Chinese and Japanese seem to be working great with the current font
 as seen in the screenshots, but there is a problem with Korean, Korean characters are not shown correctly.

![Chinese](https://user-images.githubusercontent.com/64091461/112833639-a8bb9e80-909f-11eb-88a4-adfbdfdb8962.png)
![Japanese](https://user-images.githubusercontent.com/64091461/112833649-ad805280-909f-11eb-90c5-49632349ff10.png)
![Korean](https://user-images.githubusercontent.com/64091461/112833701-c2f57c80-909f-11eb-9169-98c37778c5d9.png)

**Comment by Flameish** [comment]
I switched to DejaVu Sans which is supposed to have one of the best coverage of unicode characters. At this point I would suggest looking into Windows font fallback on your end or switching to Linux :)

**Comment by Flameish** [comment]
I've added a font selection option to the General settings which displays all installed fonts of your system. Alternatively, you can drop your own (.ttf) fonts inside the `fonts` folder (`/bin/fonts`). The [Noto CJK](https://www.google.com/get/noto/help/cjk/) font is preinstalled which should should work with Chinese, Japanese and Korean.

**Comment by Flameish** [comment]
Assumed solved. Reopen if not.
