### ISSUE TITLE
[BUG] Foxholic coming up as 'chapter list empty'

### ISSUE THREAD

**Issue by danmeiprincess** [Flameish/Novel-Grabber#139]
**Describe the bug**

**Steps to reproduce**

1. Went to Foxholic website.
2. Copied novel link.
3. Pasted in Telegram bot.
4. 

**Expected behavior**

**Screenshots**

**Platform**

**Logs**

**Additional context**

**Comment by Flameish** [comment]
See #135

**Comment by danmeiprincess** [comment]
Duplicate with a previous issue.
