### ISSUE TITLE
No words seen on CG epub

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#14]
I tried making an epub for Chrysanthemum Garden but the output epub does not contain the content of the novel: only the title and the table of contents. There are blank pages only where the words should be. I hope this would be fixed in the next update! Thank you!

**Comment by Flameish** [comment]
I don't have any problems on CG with the novels I've tried. (using 2.3.0-beta) 
Can you give me the link to the one which doesn't work?

**Comment by JasCU100** [comment]
Oh I used the 2.2.1 version. It seems that it works for the 2.3.0 version. There are words now. Thank you!
