### ISSUE TITLE
Cant get full story

### ISSUE THREAD

**Issue by christianapeach** [Flameish/Novel-Grabber#141]
Hi
I have tried to get the books i brought in wattpad and dreame but it only get free chapters in the story.why cant get the full story??
Some stories have image dialogue cant we get the images in epub. 
Thanks

**Comment by Flameish** [comment]
Did you log in and saved your cookies in the sources tab for both sites? 

I haven't actually tested either of those hosts with paid novels since I don't own any but I think someone mentioned WattPad paid stories worked.

Can you link a story which contains images so that I can take a look?

**Comment by christianapeach** [comment]
Here is the for the story contains image
https://www.wattpad.com/story/184899087-1st-novel-oxygen-%E0%B8%AD%E0%B8%AD%E0%B8%81%E0%B8%8B%E0%B8%B4%E0%B9%80%E0%B8%88%E0%B8%99-i-love-you-more-than

About wattpad and dreame paid stories is just logged in opera browser and copied the link.i don't how to save cookies in source tab.
Sorry i replied late. Thanks

**Comment by Flameish** [comment]
![image](https://i.imgur.com/fOn6P84.png)

After you saved the cookies you need to select "Use Account" before checking/grabbing a novel.

**Comment by christianapeach** [comment]
Hi 
I use novel grabber in telegram. After i say your post i tried to install it and run in pc but the .jar file didn't work.

**Comment by Flameish** [comment]
Login on the Telegram bot does not work.

`the .jar file didn't work` doesn't tell me much. If you're on Windows 10, can you try to go inside the folder where you downloaded NG and Shift + Right Click somewhere, then select Powershell. A terminal window should open. Now start the .jar from the terminal window with `java -jar NG-Launcher.jar`. Java needs to be installed but most should have it already.

**Comment by christianapeach** [comment]
Thanks 
I did as you told but cant get images and i can't get paid stories even after saving the cookies.when i log in dreame it doesn't

**Comment by Flameish** [comment]
Does WattPad Paid work?

**Comment by christianapeach** [comment]
Nope it didn't work

**Comment by Flameish** [comment]
Images on WattPad don't seem to work atm. Will take a look at that.

**Comment by christianapeach** [comment]
Hi
Now can i get images with story??

**Comment by Flameish** [comment]
I haven't looked at it yet. I will post a response here if something changes.

**Comment by Flameish** [comment]
Wattpad images should work now. Login / Paid stories still don't, I can't test it because I do not have any paid / unlocked chapters. Dreame should work through.

**Comment by christianapeach** [comment]
Hi
Thanks i tried it i am getting images also except one story i stops at chapter 6 or chapter 7 . 
The story link is 
https://www.wattpad.com/story/184899087-1st-novel-oxygen-%e0%b8%ad%e0%b8%ad%e0%b8%81%e0%b8%8b%e0%b8%b4%e0%b9%80%e0%b8%88%e0%b8%99-i-love-you-more-than

**Comment by Flameish** [comment]
Can you elaborate more /  post the error log.txt from the bin folder. It works perfectly fine for me, tried 10 chapters without problems. The files are huge through, ~200 MB.

**Comment by christianapeach** [comment]
Hi
Sorry for replying late . I have attached the text file below.
[log.txt](https://github.com/Flameish/Novel-Grabber/files/6263998/log.txt)

**Comment by Flameish** [comment]
I don't see anything in there why it shouldnt work. Try again?

**Comment by christianapeach** [comment]
Hi
I tried again but it stops at chapter 7 . If i try continuously it stops at chapter 5 or 6 . So i tried to do one chapter at a time . It takes time to appear in the folder but final it did. Thanks

**Comment by Flameish** [comment]
Yes, it takes pretty long since it needs to write a lot from the buffer into the file. Like I mentioned, ~10 chapters with images from that novel were 200 MB. I'm really also not sure why it stops, maybe take look at the task manager and see if the RAM usage is pretty high?

**Comment by christianapeach** [comment]
Hi 
When i opened to download a story it doesn't show the story pic or author name . It shows as unknown
![IMG_20210410_213259](https://user-images.githubusercontent.com/78017943/114276519-9731a980-9a44-11eb-860b-b4e9b78b7b24.jpg)

**Comment by Flameish** [comment]
Fixed
