### ISSUE TITLE
Source Webnovel Author Metadata

### ISSUE THREAD

**Issue by extraessen** [Flameish/Novel-Grabber#142]
Describe the bug
Whenever a novel is retrieved from the webnovel site, a 'More' appears at the end of author name.
If a bookmarked novel (Source Webnovel) has new chapters and is updated, it creates a new file with (AuthorName) + 'More' - (Novel Name).

Steps to reproduce

1. Check availability after entering any novel's url.
2. A 'More' will be there at the end of the author field.
 
Expected behavior
'More' shouldn't appear there.

Screenshots
![image](https://user-images.githubusercontent.com/81476483/112724568-fae2af80-8f39-11eb-8ca2-0310bbfcc7f7.png)

Platform
Java

Additional context
I checked the source of the webpage and your webnovel.class. Although I didn't understand much but maybe this will help.
![image](https://user-images.githubusercontent.com/81476483/112724712-a8ee5980-8f3a-11eb-8ea0-7cccd793a52f.png)

**Comment by Flameish** [comment]
Fixed

**Comment by extraessen** [comment]
Thank You for the work!
