### ISSUE TITLE
How do you set up the Telegram Bot?

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#143]
AS THE TITLE SAYS

(TRIED SETTING THE BOT BUT FAILED)

**Comment by Flameish** [comment]
Added a Telegram bot config panel to the settings which should make things easier. All you need to do is save your API token which you get from [@BotFather](https://t.me/botfather) and press start or you can run the bot in headless mode without the GUI from a terminal window (Powershell / cmd ) with `java -jar Novel-Grabber.jar -telegramBot` inside the Novel-Grabber `bin` folder.

**Comment by damare01** [comment]
THANK YOU! Is the wait time in hour or second? How does this help you manage/reduce traffic?

**Comment by Flameish** [comment]
If you hover over the labels it gives a bit more info. The wait time is in milliseconds so 1000 would mean 1 second per chapter. It does not reduce traffic for you but the host server you try to download from.

**Comment by damare01** [comment]
This happens to my bot if I exit the novel grabber 
![166935187_439390750702499_7674958130800244078_n](https://user-images.githubusercontent.com/81298872/112831462-89843780-90c6-11eb-9a1c-5d97a3f091d9.png)

**Comment by damare01** [comment]
can you make the bot work/running even if I exit the novel-grabber?

**Comment by Flameish** [comment]
The bot needs to run continously, you can run the bot without the GUI with the parameter -telegramBot like I said.

**Comment by damare01** [comment]
It says "Unable to access jarfile Novel-Grabber.jar"

**Comment by Flameish** [comment]
You need to be in the bin folder / navigate there. If you're on Windows, you can shift right click inside the bin folder and select "Open Powershell here" or something along those lines.

**Comment by damare01** [comment]
what does it mean "VIP file not found"?

**Comment by Flameish** [comment]
VIPs can ignore the set chapter limits. It's not needed if you leave the chapters per day / novel on unlimited through.

**Comment by damare01** [comment]
> The bot needs to run continously, you can run the bot without the GUI with the parameter -telegramBot like I said.

Sooo when I do that I can run the bot continously even when I exit the terminal?

**Comment by Flameish** [comment]
No, the VIP stuff is just a feature which I added for myself. There are ways to have a program run in the background on windows, I don't know through. Should be fairly easy to find out with a  bit of googling.

**Comment by damare01** [comment]
OHHHH! THANK VERY MUCH! SORRY FOR ALL OF THE ASKING!

**Comment by Flameish** [comment]
[Stackoverflow](https://stackoverflow.com/questions/21031171/how-to-run-a-command-in-the-background-on-windows) says `start /b java -jar Novel-Grabber.jar -telegramBot`.
Can't test it through.

**Comment by damare01** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/81298872/112838377-95c0c280-90cf-11eb-939a-acd245dc545b.png)

**Comment by damare01** [comment]
how does the Novelly Bot run continously?

**Comment by Flameish** [comment]
I just meant the program needs to run.
