### ISSUE TITLE
Better Library UI

### ISSUE THREAD

**Issue by extraessen** [Flameish/Novel-Grabber#148]
**Is your feature request related to a problem? Please describe.**
It takes a lot of time to switch to library tab if we have a lot of bookmarks. And sometimes I miss some novels while scrolling down the library which may have updates available.

**Describe the solution you'd like**
Dividing the novels into library pages. It will shorten the time needed to switch to the library tab. Also scrolling through the whole list to find a particular novel is tedious which can be avoided by creating an 'Updates Available' section which will display the novels with new chapters at the very beginning of the library.

**Additional context**
I hope I am not asking too much. Thank You for your hard work.

**Comment by Flameish** [comment]
How about adding a toggle to hide / show only entries with updates available and some form of search / sort instead of your suggested pages?

Also can you elaborate a bit more on your usage of the library? It sounds like you manually check which have new releases. What do you do afterwards? Do you visit the web page of the chapter or use the in-build functions like download / notification? I'm asking because it looks like the library is missing a function (excluding what previously mentioned) or QOL feature.

**Comment by extraessen** [comment]
> How about adding a toggle to hide / show only entries with updates available and some form of search / sort instead of your suggested pages?
 This will work fine too. It's not a big problem after all.


> Also can you elaborate a bit more on your usage of the library? It sounds like you manually check which novels have new releases. What do you do afterwards? Do you visit the web page of the chapter or use the in-build functions like download / notification? I'm asking because it looks like the library is missing a function (excluding what previously mentioned) or QOL feature for you.
 I use your in-build function to download the new chapters to their respective folder. This is where the problem comes that I have to scroll through the whole list to check for updates. And due to all of them loading at once, it takes around 5-8 secs to load the whole library tab (the reason why I said to divide the list into pages ) [Also you can blame my pc for having low specs. Sorry for that.].
![image](https://user-images.githubusercontent.com/81476483/113027519-d12ec000-91a7-11eb-8621-b3a516a92107.png)

I hope I've cleared your doubts regarding the problem I'm facing. And your suggestion also works too. In fact it will be much better than mine.

**Comment by Flameish** [comment]
5-8 seconds? How many novels do you have bookmarked? This sounds like a performance issue on my part, I never tested it with more than 6 added at a time. 

I'll take it that you don't use the automatic download of new chapters feature because you can't see which one was updated?

**Comment by Flameish** [comment]
> over 200ish

yeah... that will do it. I'll wager its reading the covers from file to buffer which takes that long. How is the memory usage? I noticed that images are pretty heavy on the memory when downloading.

**Comment by extraessen** [comment]
>How is the memory usage? 
The grabber is using memory worth 280 MB.

>I noticed that images are pretty heavy on the memory when downloading. 
I didn't understand you completely. Are you talking about downloading the novel from a website with 'get images' option enabled or the novel being loaded onto the library. If former, I seem to have no problems.

**Comment by Flameish** [comment]
I meant while downloading. But that was quite a while ago, nobody complained recently so I think its okay. 280 should also be fine.

**Comment by extraessen** [comment]
> I meant while downloading. But that was quite a while ago, nobody complained recently so I think its okay. 280 should also be fine.

Ok then. Will you close the the issue right now or should I close it? Also thanks for giving this matter a thought.

**Comment by Flameish** [comment]
I'll close it when its done after a round of feedback. Open issues are my form of TODO list.

**Comment by Flameish** [comment]
Added a search function and "only new releases" option to the library tab.
I've also added an option in the library settings tab to not display cover images, which should help with performance.

**Comment by extraessen** [comment]
Hey what about adding a filter for the novels to separate them according to their websites? Will it be troublesome?

**Comment by Flameish** [comment]
Done

**Comment by extraessen** [comment]
How about adding a completed option for novels in the library to prevent them from checking if there is any update or not?
And a manual update check option per novel.

**Comment by extraessen** [comment]
Also, in the drop down list for website filter, there is blank space for Ranobes website.
![image](https://user-images.githubusercontent.com/81476483/113710884-e48adf80-9701-11eb-9070-f3ff1839a8bf.png)

**Comment by Flameish** [comment]
Done

**Comment by extraessen** [comment]
Hello, do you have any plans on creating a dark mode?

**Comment by Flameish** [comment]
Done

**Comment by extraessen** [comment]
Hey can you give an option to change the last chapter of the novel in the library? So that we can update the novel with a new epub file from a certain chapter again without the TOC and Description pages?

**Comment by Flameish** [comment]
> So that we can update the novel with a new epub file from a certain chapter again without the TOC and Description pages?

Can you elaborate a bit more on the last bit? I'm pretty confused about the TOC / Description pages thing. I don't quite understand how they correlate to changing the last chapter. (Except a changed toc list).

But concerning the main part of changing the last chapter number and updating the ePub midway, if I get you right, is a bit complicated and not really possible without extensive changes as previously discussed [here](https://github.com/Flameish/Novel-Grabber/issues/127#issuecomment-800757688).

**Comment by extraessen** [comment]
Actually, now that I think about it it is better not to add the feature, You can leave it like that. 
So the issue that I faced goes on something like this:
1: There were 9 - 10 updates in the library. 
2: I manually updated them all. 
3: I closed the grabber and turned off the pc.
4: After 2 days, I opened the grabber again only to see the same updates for the same novels there.(I only recognized about it after downloading 2 updates).
5: Those epubs had the same chapters twice. (the epub that is created after updating from the library which don't have toc and description pages.)
6: So I tried to download them from the automatic download part in hope to update the library without getting same chapters twice. That didn't work.
7: Due to which I wanted you to make an option to be able to change the last chapter in the library so that if someone faces problem like this he/she will be able to resolve it.
8: However, you were out for few days, so I just went on and changed the last updated chapter name and number from the library json file itself manually, which resolved the issue.
![image](https://user-images.githubusercontent.com/81476483/115672639-60736180-a369-11eb-89be-d604617831a3.png)


It is okay to leave this as it is because this type of issue doesn't pop up generally. Mine seemed like an exception.
Rather, is it possible for you to beautify the Library json file? Changing the whole thing manually, while reading it in a way long horizontal line was really tedious.

**Comment by Flameish** [comment]
The problem with updating the ePub file is that there is no straightforward way of tying the file chapters (and order) to the NG chapters without inserting some kind of NG-metainformation into it. In the previous link I mentioned, a user had the issue with a "sticky" chapter (side stories) being always last place in the chapter order and would thus be always downloaded.

I'll see what I can do to pretty print the json files.

**Comment by extraessen** [comment]
As mentioned earlier, I have already resolved the issue by myself. I don't think many users will face this kind of issue. I know it will be a lot of work to do this. I don't want you trouble with those small and rare issues while you could be doing something more valuable. Thanks for the hard work.

**Comment by Flameish** [comment]
Closing this since it's getting too off-topic and the initial request(s) are implemented. Feel free to open new ones.
