### ISSUE TITLE
Flying Lines Issue

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#15]
When I tried to download from flying lines, it would say:

[INFO]Starting headerless browser...
[INFO]Connecting...
Cannot find elements when the selector is null
 
I used the 2.3.0 version.

**Comment by Flameish** [comment]
Can I get a link to the novel in question (or are none working for you?). I personally don't have a problem on Flying Lines.

Can you start the .jar from cmd/terminal and copy the console output?

**Comment by JasCU100** [comment]
I think none are working for me. I've tried with different links but it still gets the same error. I tried to star the .jar using cmd but it just opens NovelGrabber from java. I don't know where I could see the console output, though.

**Comment by Flameish** [comment]
Errors and more useful informations are displayed in cmd when you open the jar from there. You can start NovelGrabber with `java -jar Novel-Grabber.jar`.
I assume you picked the correct browser you have installed on the right side.
The links should look like this: https://www.flying-lines.com/novel/these-dangerous-girls-placed-me-into-jeopardy

**Comment by JasCU100** [comment]
Oh I tried the cmd again...here are the comments:

C:\Users\pc\Desktop>java -jar Novel-Grabber.jar
654 [pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\pc\.m2\repository\webdriver\chromedriver\win32\79.0.3945.36\chromedriver.exe
Starting ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}) on port 1954
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jan 04, 2020 10:31:24 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
45844 [pool-4-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\pc\.m2\repository\webdriver\chromedriver\win32\79.0.3945.36\chromedriver.exe
Starting ChromeDriver 79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}) on port 7356
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jan 04, 2020 10:32:09 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
java.lang.IllegalArgumentException: Cannot find elements when the selector is null
        at org.openqa.selenium.By$ByCssSelector.<init>(By.java:422)
        at org.openqa.selenium.By.cssSelector(By.java:116)
        at grabber.autoFetchChapters.processAllChapters(autoFetchChapters.java:494)
        at grabber.autoFetchChapters.downloadChapters(autoFetchChapters.java:278)
        at grabber.Download.startAutoDownload(Download.java:168)
        at gui.GUI.lambda$null$3(GUI.java:251)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Flameish** [comment]
I adjusted the selector for the chapter container. Please try again with v2.3.1

**Comment by JasCU100** [comment]
> I adjusted the selector for the chapter container. Please try again with v2.3.1

Thank you so much! It worked already!
