### ISSUE TITLE
[BUG] wuxiaworld.co chapter list empty

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#151]
**Describe the bug**
 as the title says

**Steps to reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Platform**
 telegram bot

**Logs**

**Additional context**

**Comment by damare01** [comment]
when I searched the site this what I saw 
![Screenshot (24)](https://user-images.githubusercontent.com/81298872/113286395-ba5ea980-931e-11eb-9432-0158bf5487b0.png)

**Comment by Flameish** [comment]
Looks like they're limiting the requests you can make. Try downloading NG yourself instead of using the Telegram Bot. They might also limit the number of requests you can make per minute or 10 seconds etc., maybe play around a bit with the wait time.

**Comment by Flameish** [comment]
I tested it with 100 chapters and it worked fine.
