### ISSUE TITLE
[BUG] readlightnovel

### ISSUE THREAD

**Issue by animeslash** [Flameish/Novel-Grabber#152]
**Describe the bug**

When trying to download a novel from readlightnovel, the chapter is downloaded/displayed twice.

**Steps to reproduce**

1. download a novel from readlightnovel
2. Any chapter that is downloaded will be displayed twice. I checked with calibre editor and the chapter is duplicated.

**Expected behavior**

Should only get the chapter once.

**Comment by Flameish** [comment]
Thank you for the report! For some reason they added the chapter twice, once hidden: 

![image](https://i.imgur.com/tXU4PvI.png)


I've added the 2nd one to the blacklisted tags.

**Comment by Shianelle** [comment]
Hi, I'm also getting this bug when trying to download a novel from readlightnovel.
