### ISSUE TITLE
mtlnovel cant grab

### ISSUE THREAD

**Issue by sachie007** [Flameish/Novel-Grabber#154]
Why can't I automatic grabbed in this site? it always stuck in loading. I don't even have a connection problem. 
This is the site I wanna grab https://www.mtlnovel.com/douluo-dalu-4-final-douluo/chapter-list/

What other ways I can do to grab all the chap? 

![gg](https://user-images.githubusercontent.com/51531117/113466710-6a8ff780-9470-11eb-9590-234e7e622a32.JPG)

**Comment by Flameish** [comment]
Remove `/chapter-list/` from the URL, NG works with the base novel link.

**Comment by sachie007** [comment]
It worked! Thank you very much for your immediate response.
