### ISSUE TITLE
Help required with Fanfiction.net

### ISSUE THREAD

**Issue by extraessen** [Flameish/Novel-Grabber#155]
**What is the issue?**
I am trying to download from fanfiction.net, however I can't seem to to download it all.

**Steps To Recreate and Error Log :** 
1. Input Novel Link . Eg- https://www.fanfiction.net/s/13741563/1/Re-Zero-Watching-Him-Die-Again-and-Again
Error Occurs and Log is shown below:
![image](https://user-images.githubusercontent.com/81476483/113501320-c080a000-9541-11eb-9081-e0a923a84a59.png)

2. Input Novel LInk. Eg- https://www.fanfiction.net/s/13741563/
Error shows Forbidden 403 and  chapter container is not found
![image](https://user-images.githubusercontent.com/81476483/113501501-1e61b780-9543-11eb-8fcb-c96cbb057a2e.png)

**Additional Information**
_**However**_, the full url(step-1) process _sometimes_ work without showing the error but it has the same problem and can't download the chapters as in step-2 .
![image](https://user-images.githubusercontent.com/81476483/113501456-c925a600-9542-11eb-9da8-a222fa5bcbe5.png)

**Comment by Flameish** [comment]
Fanfiction.net is no longer really supported after they put extra restrictions on their website, even more so on bots / scrapers, to push people to their app. You might get one or two chapters but after that they block your requests (403 Forbidden). It should be removed but I've forgotten about it.

**Comment by extraessen** [comment]
Ok. Thanks then.
