### ISSUE TITLE
[SITE REQUEST] Syosetu

### ISSUE THREAD

**Issue by extraessen** [Flameish/Novel-Grabber#156]
Syosetu

**Does the host have more than 15 novels?**
Yes

**Website link:**
https://syosetu.com/

**Comment by Flameish** [comment]
Syosetu has a pdf download option for each novel.

**Comment by extraessen** [comment]
yes it does but it is vertical Japanese  up to down style. And translating it is very hard. And downloading a new pdf every time  a chapter is uploaded is troublesome.

**Comment by Flameish** [comment]
Added
