### ISSUE TITLE
[FEATURE REQUEST] SUPPORT MULTIPLE DOWNLOADS ON TELEGRAM

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#157]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
 Because we can now set the bot as our own I hope that you can add a feature on the bot that allows it to download multiple files/novles at the same time. And I hope that we can set the maximum multiple download capacity.

**Describe alternatives you've considered**

**Additional context**

**Comment by Flameish** [comment]
I'll add an option for it.

**Comment by damare01** [comment]
thank you!

**Comment by damare01** [comment]
@Flameish can you notify me if you already added it please?!

**Comment by Flameish** [comment]
If it's added this issue will be closed and I'll probably write something / need feedback, you should get notified either way.

**Comment by Flameish** [comment]
Added

**Comment by damare01** [comment]
thank you!

**Comment by damare01** [comment]
how do I stop one of my downloads?

**Comment by Flameish** [comment]
If you only have one download running, /stop should stop that one. If you have multiple ones, /stop will give you a list of all downloading novels with a number in front, then you have to use that number to specific  which one you'd like to cancel: /stop 1, /stop 2 etc.
If you are using the bot in a group setting (with the /download@BotName syntax) you have to write it like this: /stop@BotName, /stop@BotName 1, /stop@BotName 2 etc.

**Comment by Flameish** [comment]
Just noticed an Out Of Memory error on my bot. This needs some more work.

**Comment by damare01** [comment]
how about when the bot finished compiling a novel, the bot will send the file to the user/group then deletes it on from the server. Likes this...

![Screenshot (32)_LI](https://user-images.githubusercontent.com/81298872/114695055-c189ac80-9d4d-11eb-9334-0b9520443887.jpg)

**Comment by Flameish** [comment]
I was a bit quick to blame the multiple download changes for that. It was actually caused by a user who tried to download a novel with huge images, added an option to disabled image download to the bot now.
