### ISSUE TITLE
[SITE REQUEST] FULLNOVELS

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#158]
**Does the host have more than 15 novels?**
 YES

**Website link:**
 [fullnovels.com](url)

**Comment by Flameish** [comment]
Really not digging that site. It's basically a bad version of NovelUpdates and it's slow as hell, it would probably take 5 minutes just to fetch the chapter list. Also you need an account to even "read" the chapters (follow the link to the actual host site), which is just a joke.
