### ISSUE TITLE
WHAT DOES THIS (protocol = https host = null) MEAN

### ISSUE THREAD

**Issue by PleaseReadMe** [Flameish/Novel-Grabber#161]
WHAT DOES THIS (protocol = https host = null) MEAN?

**Comment by Flameish** [comment]
I have no idea what you're talking about. I need some more context here.

**Comment by PleaseReadMe** [comment]
I will send a screenshot

**Comment by PleaseReadMe** [comment]
![Screenshot_2021-04-09-17-07-06-75](https://user-images.githubusercontent.com/70464689/114157346-20b67e00-9956-11eb-8145-e845f91ff230.jpg)

**Comment by Flameish** [comment]
Looks like a chapter has no valid url. The log/ terminal should have more info.
