### ISSUE TITLE
[BUG] www.lightnovelpub.com not working in telegram bot

### ISSUE THREAD

**Issue by credulous2skeptic** [Flameish/Novel-Grabber#165]
lightnovelpub.com not working in telegram bot

**Describe the bug**
When [](https://www.lightnovelpub.com/novel/dragon-kings-son-in-law-09041243) is send to @NovelGrabbyBot it says "chapter list empty".

**Steps to reproduce**
1. Open telegram bot @NovelGrabbyBot
2. send link https://www.lightnovelpub.com/novel/dragon-kings-son-in-law-09041243
3. It says Chapter list empty.

**Platform**
Android 11, Telegram Bot.

**Comment by Flameish** [comment]
Fixed
