### ISSUE TITLE
[BUG] Telegram Bot: Multiple downloads use the same progress indicator

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#168]
**Is your feature request related to a problem? Please describe.**
 Sometimes person using the telegram bot stop their downloads because they thought that their previous dowload stop progressing.

**Describe the solution you'd like**
 different progress bar for multiple downloads

**Describe alternatives you've considered**

**Additional context**

**Comment by Flameish** [comment]
Isn't there a progress indicator already?
![image](https://i.imgur.com/oHGa3jw.png)

**Comment by damare01** [comment]
yes there is, but the multiple downloads share the same progress indicator.

**Comment by damare01** [comment]
I hope that they have separate indicator

**Comment by damare01** [comment]
but if it is a hustle for you, you could opt to not do it.

**Comment by Flameish** [comment]
You're right, I forgot to adjust that. It's still storing just one message to always update. Will fix that.

**Comment by damare01** [comment]
thank you!!!!!

**Comment by damare01** [comment]
what does this mean?

![Screenshot (36)_LI](https://user-images.githubusercontent.com/81298872/115019693-1f53fb00-9eec-11eb-965f-640b23ed7cbf.jpg)

**Comment by Flameish** [comment]
The headless browser couldnt find the chapter body(css selector: article) on the page within 30 seconds. It could be a server time out or there is no article element on the page (the chapter url for that chapter is somehow wrong). I would suggest checking out that chapter manually and then if that is ok, try again.

**Comment by Flameish** [comment]
Should be fixed now!

**Comment by damare01** [comment]
@Flameish can you make a discord bot please!

**Comment by Flameish** [comment]
You already opened another issue for that, please keep these separated. It makes it way easier to keep track of what needs to be done. If there is any news, I will answer there.

**Comment by damare01** [comment]
Ok, sorry!

**Comment by damare01** [comment]
downloads still share the same progress indicator

**Comment by damare01** [comment]
ohhh never mind I just forget to update
