### ISSUE TITLE
Issue grabbing chapter list from Webnovel.com

### ISSUE THREAD

**Issue by jftroubadour** [Flameish/Novel-Grabber#17]
Novel-Grabber can't get the chapter list from Webnovel, neither manually nor automatically. The manual grab just gets navigation links from the website, while the automatic checking doesn't finish. 
Webnovel.com chapters scroll continuously, there is no "next chapter" button.

**Comment by Flameish** [comment]
Make sure you're using the "full" novel URL. The one with the name in it:
 `https://www.webnovel.com/book/12820870105509205/Supreme-Magus`
While webnovel works with just the novel number, it doesn't work in Novel-Grabber at the moment. Also keep in mind that Novel-Grabber can only grab non-vip chapters and will not count vip ones in the chapter list.

**Comment by AlenToma** [comment]
to bad it dose not inc vip content

**Comment by Flameish** [comment]
A few aggregator sites are supported through.
