### ISSUE TITLE
[BUG]Cant add web novel to library

### ISSUE THREAD

**Issue by SqueezedByte** [Flameish/Novel-Grabber#172]
**Describe the bug**
In the automatic section I can download this web novel
https://foxaholic.com/novel/a-neets-guide-to-the-parallel-world-healer-the-strongest-cheat/
it find everything without a problem but I can't click the star to add it to library.

**Steps to reproduce**

1. GO to automatic
2. copy the link in NOVEL URL
3. click on the cloud to retrieve the data
4. Try to click the star

**Expected behavior**
The star works and I can add it to library

**Screenshots**

![immagine](https://user-images.githubusercontent.com/33869313/115138632-a066db80-a02d-11eb-9ba6-5f63d0bdb64b.png)

**Platform**
Windows 10 pro

**Logs**

**Additional context**

**Comment by extraessen** [comment]
A folder can't have characters like **<>*?" : | \ /** . 
_Edit the book name and remove the "?"_ and you will be able to bookmark the novel. 
Use this as a workaround until the creator corrects this issue.

**Comment by SqueezedByte** [comment]
It worked. Thanks!

**Comment by Flameish** [comment]
Should be fixed now. Update to 3.9.2.
