### ISSUE TITLE
[BUG]「  and 」 get turned into #

### ISSUE THREAD

**Issue by krispykiq** [Flameish/Novel-Grabber#173]
Some people use "「」" instead of quotation marks and when in pdf format they appear as "#". It works when in epub or txt format and it only bugs when using pdf format.

**Comment by Flameish** [comment]
Thanks for the report! Can you provide me with a link so that I can test it?

**Comment by krispykiq** [comment]
Is it gonna be fixed soon?

**Comment by Flameish** [comment]
It will be fixed when I find the time to fix it.

**Comment by Flameish** [comment]
The launcher should download the Noto CJK (Chinese, Japanese, Korean) font automatically which will be used for the PDFs. Might help with those characters/symbols in the new update.

**Comment by Flameish** [comment]
Assumed solved. Reopen if not.
