### ISSUE TITLE
Task Scheduler

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#175]
We can use `Task Scheduler` to automatically run the bot when  the computer/server starts.

Like this (I found it while surfing)
![Screenshot (40)](https://user-images.githubusercontent.com/81298872/115376936-b88f5400-a201-11eb-8271-8b3ef70c72d2.png)

**Comment by Flameish** [comment]
Thanks for the helpful information but this doesn't belong into the issues. I'll add a section for it if I write a GitHub Wiki/Guide.
