### ISSUE TITLE
How to make a user VIP?

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#179]
The title tells my problem, please tell me!

**Comment by Flameish** [comment]
You need to create a vip.txt file inside the telegram folder with the telegram user Ids of the users(1 per line). You can see the user IDs in the telegram log file. If the number in the log has a `-` in front, then it's a download inside a group chat (groupId). After that you need to restart the bot or run the `/updateVips` command if you're an admin. 
Telegram admins can be defined in the config.ini with the parameter `telegramAdminIds=userId1,userId2,...`

**Comment by damare01** [comment]
thank you!!!

**Comment by damare01** [comment]
what is the maximum amount of vip that you can add?
