### ISSUE TITLE
newest version doesn't work but older version works

### ISSUE THREAD

**Issue by g6dragon** [Flameish/Novel-Grabber#18]
I tried the newest version it give me the JNI error has occurred ERROR but when i switch to the 2.3.4 version it works just fine

**Comment by Flameish** [comment]
Can you give me some more info about what you did when you get the error? Did you get it on startup or when trying to fetch chapters?
Automatic/Manual, Normal/Headless Host/Novel-link would be really helpful.

**Comment by g6dragon** [comment]
it's when i startup the program

**Comment by Flameish** [comment]
Can you paste the console error message? (in cmd/terminal: java -jar Novel-Grabber.jar)

**Comment by g6dragon** [comment]
![Capture](https://user-images.githubusercontent.com/61601881/75601519-e52a5e80-5a89-11ea-9302-e72a093a78ab.JPG)
yeah it doesn't work

**Comment by Flameish** [comment]
It looks like you have an old Java version installed. Check what "java -version" returns, you need SDK version 11 at least. I'm not sure why the older one works fine considering it should have been compiled for the same java version.

**Comment by g6dragon** [comment]
yeah it works now thank you! 👍
