### ISSUE TITLE
[BUG] HTML reserved charaters are not escaped in chapter titles

### ISSUE THREAD

**Issue by rvail** [Flameish/Novel-Grabber#181]
Ebook saved but TOC displays error when viewed in reader.

**Describe the bug**
[HTML reserved charaters](https://developer.mozilla.org/en-US/docs/Glossary/Entity#reserved_characters) are not escaped in chapter titles in the TOC which results in display errors in some readers. 

**Steps to reproduce**
1. Setup Novel-Graber to download https://www.wuxiaworld.com/novel/ancient-strengthening-technique
2. Set the starting and ending chapter to 30 - 33
3. Grab the chapters
4. Open epub in a reader such as marven or an editor such as Sigil.
5. See TOC has formatting error and stop displaying after chapter 32.

**Expected behavior**
TOC displays without error

**Screenshots**
Error shown by Sigil
![Capture](https://user-images.githubusercontent.com/262564/116159482-da944500-a6df-11eb-96be-f585265ae21b.PNG)

**Comment by Flameish** [comment]
The description is probably unescaped too, now that I think about it.

**Comment by Flameish** [comment]
Fixed in 3.9.4
