### ISSUE TITLE
[FEATURE REQUEST] List of Vip/s command on the bot

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#184]
**Is your feature request related to a problem? Please describe.**
 If you can please make/add a command on the bot that let's the users know who are the vip/s

**Describe the solution you'd like**
 If a user send the command /vips or /vip or anything you will like, the bot will send them the list of the vips

**Describe alternatives you've considered**

**Additional context**

**Comment by Flameish** [comment]
That would be a pretty ugly list, it would just contain the user IDs. What would you do with those?

**Comment by PleaseReadMe** [comment]
So that they will know if they are already VIP

**Comment by Flameish** [comment]
Vip restrictions are being reflected in `/limits`, if they are different.
