### ISSUE TITLE
[BUG]The Progress Indicator is Kinda Buggy

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#185]
**Describe the bug**
Sometimes the downloads will share the same progress indicator and sometimes won't, and somtimes the progress indicator won't update its progress even though it's done downloading.

**Comment by Flameish** [comment]
Please remove the issue segments which you are not going to use when writing an issue in the future.

I need some more info here. Does this happened when downloading in a personal chat with the bot or in a group?
Are multiple downloads per user running?

**Comment by PleaseReadMe** [comment]
Just the same person. It happens in the group and yes multiple downloads per user is running.

**Comment by PleaseReadMe** [comment]
And if you will ask if the finish output is sent to group if the indicator won't update its progress, the answer is yes.
