### ISSUE TITLE
[Question] How can I deploy the bot to heroku?

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#187]
How can I deploy the bot to heroku? How are you hosting your bot to run 24/7?

**Comment by Flameish** [comment]
I'm not familiar with Heroku so I can't help you there, but I run my bot on a [Raspberry Pi](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/).

**Comment by damare01** [comment]
thank you!
