### ISSUE TITLE
Request Site

### ISSUE THREAD

**Issue by rmumu** [Flameish/Novel-Grabber#19]
Please add https://wuxiaworld.site/ it has up to date release of webnovel chapters

Thank you

**Comment by Flameish** [comment]
Is there a big difference between this site and others like [BoxNovel]( https://boxnovel.com) and [NovelFull](http://novelfull.com/)? WuxiaWorld.online would need to use headless grabbing which is pretty slow in comparison.

**Comment by rmumu** [comment]
They have a support/discord channel and update faster than both sites.

**Comment by Flameish** [comment]
Check out [v2.3.7](https://github.com/Flameish/Novel-Grabber/releases/tag/2.3.7). The cover image will throw an error but you can ignore that. You can add it manually in the edit section.
