### ISSUE TITLE
[Question] How can I modify the bot?

### ISSUE THREAD

**Issue by PleaseReadMe** [Flameish/Novel-Grabber#191]
How can I remove a source? I want to remove a source so that the bot will only crawl the site that I did not remove.

**Comment by Flameish** [comment]
Just remove the file from the sources folder.

**Comment by PleaseReadMe** [comment]
> Just remove the file from the sources folder. (source files end in .class)

Thank you very much 😊

**Comment by Flameish** [comment]
Just keep in mind that the updater/launcher will re-download them.
