### ISSUE TITLE
[FEATURE REQUEST]Split downloaded epub per volume or per 100 or so chapter

### ISSUE THREAD

**Issue by mskomek** [Flameish/Novel-Grabber#195]
Some of the novels have very huge number of chapters (2000-3000) and that casues long loading time because i read from my phone.Is it possible to split epub per 100 chapters or so.Then i can or someone who read from the phone can read more smothly.

**Is your feature request related to a problem? Please describe.**
There is not a problem just very convenient feature.

**Describe the solution you'd like**
Option to choose split epub according to your will for example 100 chapters per epub or 1 volume per epub and per epub should have cover page and introduction etc.

**Describe alternatives you've considered**
I dont know you know there is another app called lightnovel-crawler that has this feature but it split according to volume so sometimes it wont work beacuse site has novel as a bulk.1 epub has 3000chapters it took too long to load.

**Additional context**
Thank you for creating this app it is very usefull and well made.

Best regards

**Comment by Flameish** [comment]
This sounds like a eReader problem to me. I can recommend Moon+ Reader on Android, maybe try that? Alternatively you can always download chapters in steps.

**Comment by mskomek** [comment]
i mean if there is a option that makes separately epubs that would be nice rather than doing your own like you choose eacsh epub will have 100 chaps so if there are 1000 chapters then there would be 10 epub like "something something 1-100.epub, something something 101-200.epub" etc

**Comment by johnveyron** [comment]
@mskomek 
Using moon reader or pocket-book reader. Open epub like instant, then what's your reader?

**Comment by budikesuma** [comment]
@mskomek 
Using moon reader or pocket-book reader. Open epub like instant, then what's your reader?
`the feature something of Splitting the novel into several parts is useless for me, even I really support a complete epub until it's finished even though it has ten thousands of chapters, Lol .. n I have many of it`
