### ISSUE TITLE
[BUG] Can't get chapters from Dummy novels

### ISSUE THREAD

**Issue by graciagraciagracia** [Flameish/Novel-Grabber#198]
**Describe the bug**
 Unable to download from Dummy Novels. The progress of generating the chapters are okay but failed when it's time to download. 

**Steps to reproduce**

1. Paste link (e.g. https://dummynovels.com/novel/monster/)
2. Chapter generation (e.g 39c)
3. Novel download (cannot proceed)

**Expected behavior**
 Expected that after generating the chapters, it should naturally proceed to downloading the chapters. 

**Platform**
 Telegram Bot

**Comment by Flameish** [comment]
Thanks for the report!
It seems like they changed their site a bit and the old chapter selector doesn't work anymore. Will fix later today.

**Comment by Flameish** [comment]
Sorry for the delay. Fixed now!

**Comment by graciagraciagracia** [comment]
Thank you for your hardwork!
