### ISSUE TITLE
Is there a way to manually add chapters?

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#20]
Hello! I was hoping if maybe there could be a way to manually add missing chapters? Because sometimes the website does not include a chapter in their list of contents or forgot to link it. It would also be cool if there's a feature where we could rearrange some chapters and not just invert chapter order. 

Thank you very much!

**Comment by Flameish** [comment]
Hey, thanks for your feedback! I will see what I can do about a dedicated chapter-order editing window. For now you could select the calibre export option and manually edit the outputted Table of Contents.html file and convert it in Calibre to EPUB. Remember to set the "Number of links to add to Table of Contents" under "Table of Contents" to 0 when converting in Calibre if you go for this approach.

**Comment by Flameish** [comment]
I quickly threw something together. Check out [2.4.0](https://github.com/Flameish/Novel-Grabber/releases/tag/2.4.0).

**Comment by JasCU100** [comment]
> I quickly threw something together. Check out [2.4.0](https://github.com/Flameish/Novel-Grabber/releases/tag/2.4.0).

Thank you very much!

**Comment by JasCU100** [comment]
Hello! I noticed that the option to remove/add and rearrange chapters could only be found in the automatic tab. Could there please be an option also for the manual tab? Thank you!

**Comment by Flameish** [comment]
Working on it!

**Comment by JasCU100** [comment]
> Working on it!

Thank you!

**Comment by Flameish** [comment]
I apologize for the long wait. I implemented chapter adding and rearranging for both tabs. Check out v2.4.2

**Comment by JasCU100** [comment]
Thanks for the update! But I can't seem to get links from the manual tab when I enter any websites, even supported ones. The 'links' page stays blank. I get [Error] Null in the log. And I also noticed that when I try to download from CG in the automatic tab, the title becomes the name of the first chapter.

**Comment by Flameish** [comment]
I fixed the title selector for CG, just restart Novel-Grabber to get the updated selector list. A fix for the manual tab will come later today.

**Comment by Flameish** [comment]
Manual grabbing should be fixed in 2.4.3 again!
