### ISSUE TITLE
[FEATURE REQUEST] When adding titles to the pages, make them<h1> tags. 

### ISSUE THREAD

**Issue by Xziden** [Flameish/Novel-Grabber#203]
In the automatic grabbing of novels, there's a checkbox to add chapter titles, is it possible to add some customization options for that? Things such as making them <h1-6> tags, just putting the chapter title/number, etc.?

**Comment by Flameish** [comment]
Yeah thats easy to add. I just need a few concrete suggestions for options. 

Chapter title / name are a bit different through since theres just the internal numbering. (First chapter on the list is 1 next is 2 etc.)

**Comment by Xziden** [comment]
Would it just be possible to make it so that the added chapter title can be customized? Currently, it's <span> but could we just customize the css or something similar?

**Comment by Flameish** [comment]
Easiest way would be a general selection: Choose between h, span etc. then centered/underlined, size. A fully custom html/css string you can enter where the title will be inserted would also be possible. Maybe both.

**Comment by Xziden** [comment]
If possible, that would be great!

**Comment by Flameish** [comment]
I've moved the settings concerning the novel creation into a separate settings tab and added some rudimentary title editing. For now you can select between `span` which is like the previous default, `h1` and `custom` where you can enter html code with a variable for the chapter name (%s).
