### ISSUE TITLE
[SITE REQUEST] lightnovelpub.com

### ISSUE THREAD

**Issue by dervdinditii** [Flameish/Novel-Grabber#204]
Light Novel Pub

**Does the host have more than 15 novels?**
Yes

**Website link:**
https://www.lightnovelpub.com

**Comment by posiaden123** [comment]
working on it

**Comment by dervdinditii** [comment]
when I use "Automatic", it keeps saying "Host not supported"
in "Manual", it can access but it only gives links up to 100th chapter

**Comment by posiaden123** [comment]
![image](https://user-images.githubusercontent.com/64321652/120696052-14443280-c47a-11eb-98d8-28506f1d8099.png)
it's there under sources
make sure you're using the correct url

**Comment by Flameish** [comment]
Can confirm that it works. Tried it with this url: https://www.lightnovelpub.com/novel/i-am-a-gao-fushuai-villain
