### ISSUE TITLE
[SITE REQUEST] 78zaotl

### ISSUE THREAD

**Issue by graciagraciagracia** [Flameish/Novel-Grabber#206]
78zaotl

**Does the host have more than 15 novels?**
 No. Just 6 at the mo. The site was just starting so it's normal to have few novels, but the translated novels are very good! It's a shame if it's not included. 

**Website link:**

https://www.78zaotl.com

**Comment by posiaden123** [comment]
Side is kinda weird, should be added in #205

**Comment by Flameish** [comment]
Added

**Comment by graciagraciagracia** [comment]
Is  the site already added on the  telegram bot? Still not included in source list.  Thanks!!!
