### ISSUE TITLE
[BUG] Library Function keeps breaking down randomly

### ISSUE THREAD

**Issue by Altair2169** [Flameish/Novel-Grabber#209]
**Describe the bug**

the novels added to the library sometimes get their previous content deleted and only the new chapters remain

**Steps to reproduce**

1.  Add novel to library
2.  Novels gets updated

**Expected behavior**

new chapters should be added to the previous ones

**Screenshots**

**Platform**

Windows 10 , jdk 14

**Logs**

https://drive.google.com/file/d/15BsBPVX2Cr5tS6dBW66PjZ6Vsj9tg3ou/view?usp=sharing

**Additional context**

**Comment by Flameish** [comment]
NG shouldn't delete anything; if new chapters are downloaded, it will add them to the old file. From the logs you can see that the old file wasn't found. Make sure that the files are at the correct place as set in the save location setting. 

` [2021-05-24T00:20:54] Could not read old book file. `
`[2021-05-26T23:15:58] Could not read old book file.`

You're log is also pretty large from a lot of network errors, feel free to delete it. NG shouldn't be that verbose in the newer versions.

**Comment by Altair2169** [comment]
>  NG shouldn't delete anything; if new chapters are downloaded, it will add them to the old file. From the logs you can see that the old file wasn't found. Make sure that the files are at the correct place as set in the save location setting. 
> 
> ` [2021-05-24T00:20:54] Could not read old book file. `
> `[2021-05-26T23:15:58] Could not read old book file.`
> 
> Your log is also pretty large from a lot of network errors, feel free to delete it. NG shouldn't be that verbose in the newer versions.
> 
> 
> 
> 

Will delete the old logs but I haven't touched the files at all. I was just keeping track of the file sizes and if it was too small I opened it to check the content. So idk why it's throwing this error

**Comment by Flameish** [comment]
I've added a little more info to that message, it shows now which file is being tried to read and if there is a file permission issue. This should make it easier to compare the old read path to the new file path. Please update.

**Comment by Altair2169** [comment]
Hi sorry for the late reply. But I'll keep track of the updates now and If it again breaks I'll comment here. Thanks

**Comment by Flameish** [comment]
I'm closing this for now but feel free to reopen it if you notice anything!
