### ISSUE TITLE
Trouble Opening Newer Novel-Grabbers

### ISSUE THREAD

**Issue by Synalith** [Flameish/Novel-Grabber#21]
I tried several versions of the program and they all gave me the error "Unable to run jarfile novel-grabber.jar" when I tired to open them with CMD, trying without CMD gave me a JNI error but I uninstalled java and reinstalled and it did not fix. I finally got version 2.3.4 to work but the newer ones did't. I don't know why because the Error it gave does't really explain much. Just thought I'd leave this here since I'd like to use the never versions as they come out. Thank you for your time.

**Comment by Flameish** [comment]
If this is the same error someone else had, it's because you're using an older Java version (java only really updates to java 8 while Novel-Grabber uses java 11). To install Java 11 you would need to install it via OpenJDK. I will see if I can compile Novel-Grabber for java 8.

**Comment by Flameish** [comment]
Please check if the new [v2.4.1](https://github.com/Flameish/Novel-Grabber/releases/tag/2.4.1)works for you.

**Comment by Synalith** [comment]
> Please check if the new [v2.4.1](https://github.com/Flameish/Novel-Grabber/releases/tag/2.4.1) works for you.

yes this one works with just java 8. I didn't know that java 8 was an old one.

**Comment by shimizurei** [comment]
I think this issue can be closed.
