### ISSUE TITLE
[SITE BROKEN] Shubaow.net

### ISSUE THREAD

**Issue by azurymous24** [Flameish/Novel-Grabber#214]
**Describe the bug**

**Steps to reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Platform**

**Logs**

**Additional context**

**Comment by Flameish** [comment]
Works perfectly fine for me. Can you post your novel link?

**Comment by Flameish** [comment]
A valid novel link for Shubaow looks like this : https://www.shubaow.net/17_17921/
Closing for now, feel free to reopen if anything else comes up.
