### ISSUE TITLE
[SITE BROKEN] WattPad.com

### ISSUE THREAD

**Issue by christianapeach** [Flameish/Novel-Grabber#218]
**Describe the bug**

I didn't use it for past 2 to 3 weeks . Yesterday i opened telebot to download a story .when i copy paste the link it shows chapters empty. So i tried java it shows the story name no image or anything. Please look into . Thanks for creating such a helpful tool. Thanks
![Screenshot_2021-06-11-08-07-16-503_org telegram messenger](https://user-images.githubusercontent.com/78017943/121674301-826aa400-cacf-11eb-91e0-88045df84d2c.jpg)

**Steps to reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Platform**

**Logs**

**Additional context**

![IMG_20210612_092858](https://user-images.githubusercontent.com/78017943/121764313-91e5fd80-cb60-11eb-8b78-eb286a293784.jpg)

**Comment by JoyceEstrada13** [comment]
Now in telebot, when I also send link from wattpad. Host not supported: wattpad.com, it is what it say. 
Can I ask if  you can restore in sources the wattpad?
Thank you for this wonderful helpful tool.

**Comment by christianapeach** [comment]
Yes @JoyceEstrada13  yesterday when i check it shows wattpad as one of the source but today it changed. Please include wattpad . Please @Flameish

**Comment by Flameish** [comment]
I removed it for now because it's now working. Will be re-added once it's fixed

**Comment by christianapeach** [comment]
Sorry for late replying . Looking forward when you fix this issue. Thank you

**Comment by Flameish** [comment]
Fixed

**Comment by christianapeach** [comment]
Thanks
