### ISSUE TITLE
[SITE REQUEST] Active Translations

### ISSUE THREAD

**Issue by Mockii7** [Flameish/Novel-Grabber#219]
Active Translations

**Does the host have more than 15 novels?**
Yes, 20 novels are currently translated and hosted by them.
Can't find their novels on any aggregator sites either.

**Website link:**
https://a-t.nu/

Would be much appreciated, they unfortunately don't allow users with VPN's on their site and it is a bit annoying to turn it on and off again whenever I want to read something from their site.

**Comment by Flameish** [comment]
Added / updated. Apparently they moved domains and the previous one was already supported.
