### ISSUE TITLE
[SITE BROKEN] secondlifetranslations.com

### ISSUE THREAD

**Issue by graciagraciagracia** [Flameish/Novel-Grabber#221]
**Describe the bug**
 There are 2 problems: (1) Cannot process oneshot novel — with just 1 chapter — chapter list empty; link is https://secondlifetranslations.com/ijtal/ijtal-oneshot/
(2) Process of chapter list OK, there's a retrying process but still failed to download the whole novel; link is https://secondlifetranslations.com/novel/slve-president-master-secretary/

**Platform**
 Telegram 7.3.1 bot

**Comment by Flameish** [comment]
1) That not actually the novel link. Try: https://secondlifetranslations.com/novel/ill-just-take-a-lick/
2) I've updated the chapter body selector. Please try again.
Telegram Bot will be updated later today.

**Comment by graciagraciagracia** [comment]
Alright! Thank you for your hard work!
