### ISSUE TITLE
[SITE REQUEST] https://www.worldnovel.online/

### ISSUE THREAD

**Issue by budikesuma** [Flameish/Novel-Grabber#223]
Hi Devs,
Please add site: https://www.worldnovel.online/
It has a lot of novels in specific language. 

Novel link: https://www.worldnovel.online/novel/my-disciples-are-all-villains/

**Comment by budikesuma** [comment]
never respond yet, open new reqs then.

**Comment by Flameish** [comment]
New site requests are pretty much not on the todo list right now. Basically, I will do some when I feel like it from time to time.
