### ISSUE TITLE
COMRADEMAO issues due to new website desing

### ISSUE THREAD

**Issue by apaxc** [Flameish/Novel-Grabber#24]
After trying to download novels from Comrademao this is what happens.

[INFO]Fetching novel info...
[ERROR]HTTP error fetching URL

**Comment by Flameish** [comment]
ComradeMao is using CloudFlare at the moment which renders static grabbing impossible. I've made adjustments to the headless grabbing(which can bypass CloudFlare) in v2.4.2.
Make sure you tick the box "use headless grabbing" and pick your browser before fetching the novel info and chapters.
