### ISSUE TITLE
[SITE BROKEN] Active translations (on desktop app only, ver 3.9.4)

### ISSUE THREAD

**Issue by frykauf** [Flameish/Novel-Grabber#243]
the telegram bot still handles a-t.nu site perfectly.

**Comment by Flameish** [comment]
Seems fine for me. Did u use the updater recently?

**Comment by frykauf** [comment]
Oh. Starting via NG-Launcher.jar updates the app. I was wondering how the app does updating, I’m so used to always lunching the final jar that I didn’t think the jar launcher coud do that.

Can you please clarify it in the Readme for dummies like me? :D

**Comment by Flameish** [comment]
I thinking of combining them so that main jar can see if updates are available and then start the updater.
Will add it to the readme till then.

**Comment by frykauf** [comment]
Yeah, that seems like a good move, especially if someone just downloads the jar and moves it elsewhere/ is used to just using the downloaded jar to always launch the app - which might be most people.
