### ISSUE TITLE
[BUG] Library overwrites old epub/chapters

### ISSUE THREAD

**Issue by Kapperhino** [Flameish/Novel-Grabber#257]
When you download new chapters through library the old chapters/epub gets deleted

Lets say my last chapter is 14 and I have chapter froms 1-14 in my epub
![image](https://user-images.githubusercontent.com/19327337/127204559-e3872333-2fd6-4e34-bf4c-9fbf1a0d2700.png)
![image](https://user-images.githubusercontent.com/19327337/127205015-d1e49c64-2b34-4fad-85f9-c0f722b7ee69.png)

and then when I download the new chapter the old chapters/epub gets deleted and my epub has only 1 chapter.
![image](https://user-images.githubusercontent.com/19327337/127204610-4fca24ed-fca7-486b-a46e-118947cab4c3.png)

I think it just overwrites the previous epub file with a new one.
 I think it started with update 3.10.1 because with version 3.10.0 and even the earlier ones it didnt happen.

**Comment by Flameish** [comment]
Thanks for the quick report! I released a hotfix, please update.

**Comment by Kapperhino** [comment]
It still does the same thing but I found out that it doesnt work only with this
![image](https://user-images.githubusercontent.com/19327337/127224133-49d4bcc1-97ac-45e2-897e-24e5c1868725.png)
or this
![image](https://user-images.githubusercontent.com/19327337/127224216-f241590f-8304-4355-8241-41f3573e4d29.png)

but when I select <author> - <title> or the other one then it works

**Comment by Flameish** [comment]
There shouldn't be any difference between those options; it works fine for me. When the library tries to write the EPUB file it will first try to find a previous file with the same name as this new one and then update that instead, so you can't change the filename format on the fly.

It might be worth to take a look at the log file, it should say something about not being able to find a previous file.

**Comment by Kapperhino** [comment]
Weird... thats exactly what I was getting in the log file but only when my epub was named after title but today its working without problems.

Anyway thank you for the fast fix!
