### ISSUE TITLE
NG-exe is missing from the files.

### ISSUE THREAD

**Issue by kingofmortals** [Flameish/Novel-Grabber#263]
There is no NG-Exe available in the NG-master Grabber folder.

![image](https://user-images.githubusercontent.com/85612744/128494357-0eacf87d-9794-4816-b116-f08770e4d03b.png)

**Comment by Flameish** [comment]
There is no compiled version in the GitHub repository itself, those are bundled with the updater inside zip files on the [release page](https://github.com/Flameish/Novel-Grabber/releases/tag/3.9.2).

**Comment by kingofmortals** [comment]
I downloaded the Zip folder and there is no installer in the folder.  I have used the Grabber before this instance. But, the installer is missing from the folder now. 
![image](https://user-images.githubusercontent.com/85612744/128498971-068f021b-da97-46d2-8fca-afafa6cf54a8.png)

**Comment by Flameish** [comment]
The updater (which updates the main program and supported sources) is called NG-Launcher.jar, inside the bin folder is the actual program. There is no .exe. Jar files are like exe for java.

**Comment by kingofmortals** [comment]
Sorry for being redundant. But, I can't see any NG-jar file launcher. There's another Rar folder as I extract it. It's saying a path cant be found and seems to be corrupted.

![image](https://user-images.githubusercontent.com/85612744/128500978-dfa24a64-67d2-4665-bfb7-1ed39f62580b.png)

**Comment by Flameish** [comment]
![128498971-068f021b-da97-46d2-8fca-afafa6cf54a8](https://user-images.githubusercontent.com/47372220/128507443-d77e569f-97fb-4422-ba5e-6ba5975658a5.png)

That's the Launcher/Updater. It's type is being misidentified, make sure Java is installed. If you do have Java installed and it's still associating .jar files with something else, you can right click it the jar file -> open with -> Java. 

On a side note, I would also suggest enabling file extensions in your explorer.

**Comment by kingofmortals** [comment]
Thank you very much. It was not identifying jar file. it worked. thanks for your time.
