### ISSUE TITLE
[SITE BROKEN]  Ficfun.com

### ISSUE THREAD

**Issue by JoyceEstrada13** [Flameish/Novel-Grabber#264]
Ficfun.com

**Additional information**
In telegram bot. When i'm sending the link, it doesn't reply.

**Comment by Flameish** [comment]
I think they switched to being fully app based. If you navigate to ficfun.com it will just say to download their Android/iOS App and when I do go to a direct novel link, the chapters are not being loaded. Is this also the case for you?

**Comment by JoyceEstrada13** [comment]
Actually when i open it in browser the copy link from the app, it actually open. Actually, when i first try sending the link in the bot. It reply, and send the file, but in the second time. It doesn't reply anymore.

By the way, THANK YOU for this wonderful bot and app.
