### ISSUE TITLE
[SITE BROKEN] lightnovelpub tag updation

### ISSUE THREAD

**Issue by Altair2169** [Flameish/Novel-Grabber#268]
SITE: https://www.lightnovelpub.com/

**Additional information**

they have shifted the chapters in a new container for e.g

this was the original url ```https://www.lightnovelpub.com/novel/chronicles-of-primordial-wars-19072354``` but now its changed to ```https://www.lightnovelpub.com/novel/chronicles-of-primordial-wars-19072354/chapters```.

Notice the /chapters there. while the scraping still works if I manually point it there but the novel name , author name and novel cover gets messed up

**Comment by Flameish** [comment]
Fixed

**Comment by Altair2169** [comment]
Thanks!
