### ISSUE TITLE
[SITE BROKEN] WNMTL.org

### ISSUE THREAD

**Issue by TheMystery28** [Flameish/Novel-Grabber#269]
In the Novel-Grabber list, it is specified that it is compatible with wnmtl.org

However, I've been trying for days with different configurations and different CSS which I copied using the inspector. but the only result I get is an epub that doesn't contain the text of the chapter but only the rest of the text such as "Next Chapter". I tried to get inspiration from the example on the site below.
https://github.com/Flameish/Novel-Grabber/issues/62#issuecomment-730305855

I think it's related to Javascript but I'm not an expert on it.

Could you please enlighten me.

**Comment by Flameish** [comment]
There is currently no automatic check in place to verify if all sources work, so they are 'working' until someone reports that it doesn't. In this case it seems that they switch stuff on their website around so the old script didn't work any longer. I adjusted it and it should work now, please use the Launcher to fetch the new update.

To answer your manual grabbing question, they load basically everything via JavaScript on runtime so it's not that straight forward to get everything. Even basic metadata like title and author are fetched.

**Comment by posiaden123** [comment]
be careful using wnmtl as well, they do have a cloudflare service that checks the browser sometimes
