### ISSUE TITLE
Bug when Manual Scraping From Links With Repeating Chapter Names

### ISSUE THREAD

**Issue by brandontruongg** [Flameish/Novel-Grabber#27]
When you manually scrape from a table of contents link and there is repeats in the link text (e.g. there is multiple "Chapter 1"s) the html file of these will all be named "Chapter-1.html" and therefore only the last-scraped "Chapter 1" will be used for all chapters called "Chapter 1". A situation where this commonly occurs is when the novel is split of into volumes and the link text does not include the volume and the chapter count is reset after every volume.

This issue only occurs starting from this commit: https://github.com/Flameish/Novel-Grabber/commit/1e8e89fb728590302631b43386e44ba3b4e6375a

Before this commit each chapter has a unique, always incrementing 5 digit prefix (e.g. "00001-Chapter-01.html") and therefore does not have this bug.

**Comment by Flameish** [comment]
Thank you very much for your extensive bug report! I've added the old file naming back in and pushed the commit. A new compiled build will follow later today.
