### ISSUE TITLE
[FEATURE REQUEST] Separate file for each chapter option

### ISSUE THREAD

**Issue by mp3096** [Flameish/Novel-Grabber#275]
I have novel Website some website have cloudflare etc so its hard to scrape from them to own website.
I have used your plugin was hoping you could add feature called - Seprate file for each chapter.
Basically, it will create. txt file for each chapter like chapter 1, chapter 2, etc all .txt. 
Thank you.

**Comment by Flameish** [comment]
That's already supported.
![image](https://user-images.githubusercontent.com/47372220/131264573-ed1b74e3-5a02-4aa2-af6b-b073d0286383.png)

**Comment by mp3096** [comment]
can u also add seprate folder followed by name like this in picture
https://prnt.sc/1qrfte8

**Comment by Flameish** [comment]
I don't quite see a reason to add this; you can do archive this effect pretty easily with a script/re-namer. Furthermore I'm not working on this version of Novel-Grabber much.
