### ISSUE TITLE
Login account

### ISSUE THREAD

**Issue by ml9021504** [Flameish/Novel-Grabber#279]
Hi how can I login an account to download paid stories?

**Comment by rektpartyaftermath** [comment]
i think its gonna be really complicated to do.

**Comment by Flameish** [comment]
You can try to store your login cookies in settings for each source, either manually or via the popup window and clicking save cookies. I cant gurantee that it works because i don't have accesse to accounts with unlocked stories to test with.

**Comment by ml9021504** [comment]
Thank you. I already downloaded the unlock chapters that I need thru your program.
