### ISSUE TITLE
Combing novel with the updates

### ISSUE THREAD

**Issue by Killo1988** [Flameish/Novel-Grabber#281]
When the novel is updated it does not put it together with the original file is there a way to combine them so that the original file it updated to the latest release or am I just missing something?

**Comment by Flameish** [comment]
If NG can find the previous epub, new chapters should be added to the end of it. Maybe check for an error message "could not find old file" in the log.

**Comment by Killo1988** [comment]
[2021-09-06T14:46:21] No accounts file found.

**Comment by Killo1988** [comment]
So I needed to go to the file created under my user name not the file that I had on my desktop to get it to check the files in the account.

**Comment by Flameish** [comment]
> No accounts file found.

This message is irrelevant, it always prints that if you don't have any account cookies stored for a source. 

Just to make sure we are on the same page: You are talking about the library fetching newly released chapters for a favourited novel?  The "normal" download can't update files. (The next major release of NG will be able to, but that still a bit off)

**Comment by Killo1988** [comment]
Yeah talking about favorited novels figured out that I had created a file for NG-Launcher.jar and was launching from that on my Desktop which wasn't the same as the file created under my username file. So I launched the .jar from the user/bin file which allowed to to find the account cookies I guess hard to explain would have to show to make this a lot easier.

**Comment by Flameish** [comment]
With 'created file' do you mean a shortcut to run NG? It can be a bit picky with where it is started from because of relative paths (bad programming, my bad), ideally you want to run the .jar from inside the NG bin folder.

 If you click on a novel in the library tab, it shows a save location path, it will look for the old file there and update the EPUB with the matching file name.

**Comment by Killo1988** [comment]
Yeah found it after looking and just started to run the NG launcher through the bin file and its all good free program so can't complain =) love the program itself just tying to get my Librera app and google sync to play nice so I can update it there and read the updates without having to copy paste every update.

**Comment by Flameish** [comment]
Sounds good!
