### ISSUE TITLE
How to download unlocked stories in telegram bot using the program? Do you have contact page for personal inquiries?

### ISSUE THREAD

**Issue by ml9021504** [Flameish/Novel-Grabber#282]

**Comment by Flameish** [comment]
I don't think you can use an account when grabbing via the Telegram Bot currently. It would need a quick fix on this [line](https://github.com/Flameish/Novel-Grabber/blob/2e4fed21450e1b401a149e9c476633bd4dcf906b/src/main/java/bots/telegram/DownloadTask.java#L75) to make it work with the cli argument `-login` from Telegram.

For personal inquiries you can send me an email directly, you can find it at the top of each [commit](https://github.com/Flameish/Novel-Grabber/commit/4c8112f0ffd56df37ff44cf1a8611fa99ea94f2f.patch). (not writing it here for spam bot reasons)

**Comment by ml9021504** [comment]
Noted. Thank you.
