### ISSUE TITLE
[SITE REQUEST] Manual downloading is giving an error with ToC URL

### ISSUE THREAD

**Issue by captain-muchiko** [Flameish/Novel-Grabber#286]
Hi,

The website [OTS](https://ontimestory.eu/) is giving a forbidden error when trying the manual download option (for any link).

Example: When adding [this](https://ontimestory.eu/index.php/devil-venerable-also-wants-to-know/) URL using the manual option, the "Get links" button doesn't respond with any result.

The log just shows this line: [2021-09-10T08:02:41] Forbidden! (403)

**Platform**
Windows 10, Java Version 8.

Any help with this would be appreciated, thanks!

**Comment by Flameish** [comment]
Forbidden 403 means that the server blocked your request, probably because of bot detection. You might have better luck using Headless Grabbing.

**Comment by captain-muchiko** [comment]
Yes! With Headerless Browser worked! (It had never occurred to me using that option, but now I will consider it in case I have the same problem in the future).

Thank you!

**Comment by Altair2169** [comment]
Can you in life headerless option for automatic grabs too? It would be nice to get the library features working with these sites. Thanks

**Comment by Flameish** [comment]
Headless Grabbing has nothing to do with the library and you can't add manual grabs to the library.

**Comment by Altair2169** [comment]
I meant if it works on some sites maybe if possible add that option when trying to use automatic grabs? and some books already added to the library may also start grabbing chapters again if headerless option works for those sites

**Comment by Altair2169** [comment]
Also since some sites use CloudFlare, maybe an option of having users manually navigate through cloudflare before grabbing the links should be there? Tachiyomi (a manga reading app) generally works like that, after manually navigating the captcha, the sites work as intended

**Comment by Flameish** [comment]
Cloudflare can detect Headless grabbing in most cases. I haven't been able to make it work reliably.
