### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#29]
Hello! I would like to request if we could just copy and paste a list of URL links and their chapter names in the automatic/manual tabs so that it would be easier to edit? 
For example: 
<https://www.website.com>Chapter 1- Chapter Name

It's just that there are some websites that do not automatically add new chapters and adding them always every time I try to download is becoming time-consuming. 

I would also like to request if https://foxaholic.com/ could be added to the list of websites supported? Thank you very much! :)

**Comment by Flameish** [comment]
You're talking about the manually adding/editing chapters/order window? How about a new dialog window with 2 areas to paste lines in where one corresponds to a chapter name/link on the other side?

Will add foxaholic.

**Comment by JasCU100** [comment]
> You're talking about the manually adding/editing chapters/order window? How about a new dialog window with 2 areas to paste lines in where one corresponds to a chapter name/link on the other side?
> 
> Will add foxaholic.

Thank you! 
Yes, the adding/editing chapters window. Like maybe there could be an option to get lines of code when the program gets the chapters and I could save these code to notepad and then just copy/paste it to a window?

**Comment by Flameish** [comment]
I removed the (single) chapter adding function and replaced it with a new window where it lists all chapter names and links side by side. You can just paste your custom names and links at the end. This also enables you to save the names/links which the grabber stores internally.

![image](https://user-images.githubusercontent.com/47372220/82593010-13f43480-9ba2-11ea-8d4c-6722e7759d39.png)

Is this what you had in mind?

**Comment by JasCU100** [comment]
> I removed the (single) chapter adding function and replaced it with a new window where it lists all chapter names and links side by side. You can just paste your custom names and links at the end. This also enables you to save the names/links which the grabber stores internally.
> 
> ![image](https://user-images.githubusercontent.com/47372220/82593010-13f43480-9ba2-11ea-8d4c-6722e7759d39.png)
> 
> Is this what you had in mind?
> 
> I've added limited support for Foxaholic (headless only atm)

Yes, this is what I had in mind. :)

**Comment by JasCU100** [comment]
Thank you for the update! I recently had an issue though with CG...there are frequent times when I would encounter this error, especially with longer chapters: 

Fetching latest selector JSON from GitHub...
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://blahblahblah
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
        at grabber.Chapter.saveChapter(Chapter.java:43)
        at grabber.Novel.downloadChapters(Novel.java:97)
        at gui.GUI.lambda$null$2(GUI.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
