### ISSUE TITLE
[BUG] Add chapter title option is not working with TXT output

### ISSUE THREAD

**Issue by ml9021504** [Flameish/Novel-Grabber#291]
Please includes the chapter titles in txt format output. 

**Is your feature request related to a problem? Please describe.**
When reading the output it is confusing when the chapter titles are missing. 

**Describe the solution you'd like**
Request to include the chapter titles.

**Comment by Flameish** [comment]
Normally they should be added when selecting `Add chapter title` in the options but that's not working apparently.
