### ISSUE TITLE
[FEATURE REQUEST] Novel Updates x Blogspot

### ISSUE THREAD

**Issue by TheMystery28** [Flameish/Novel-Grabber#294]
Many novels are on blogspot, but there is usually no way to download them. I noticed that novelupdate collects the chapter links and keeps them up to date so I'm wondering if it's possible to cobble together a feature that allows you to collect all the links and then download the novel. I don't know if it's possible and that's why I ask.

**Comment by Flameish** [comment]
Manual grabbing was designed for this.

**Comment by TheMystery28** [comment]
I see... I will check that. Thanks.
