### ISSUE TITLE
Epub creation failure on Chrysanthemum Garden

### ISSUE THREAD

**Issue by MylesC-cs** [Flameish/Novel-Grabber#30]
Hello,

I am attempting to create epubs for several novels on CG and some are not coming out in a readable form. It works for some titles however titles such as this one: 

https://chrysanthemumgarden.com/novel-tl/mpcd/

Have an issue with the epub. The reader I am using is ibooks on a 2018 ipad pro running the latest ios.

**Comment by Flameish** [comment]
This is a known issue (#22 #23). Current work around would be to import/clean it in Calibre/Sigil. Or using a different eReader.

**Comment by MylesC-cs** [comment]
Understood, thanks. I am offloading to kybooks which seems to be more tolerant than ibooks
