### ISSUE TITLE
[SITE REQUEST] https://web.archive.org/web/20161119214524/http://www.wuxiaworld.com/cdindex-html/

### ISSUE THREAD

**Issue by budikesuma** [Flameish/Novel-Grabber#315]
`https://web.archive.org/web/20161119214524/http://www.wuxiaworld.com/`

Hello Devs...
since the completed novel in WW locked by karma.  So working from web archive sources will solve the problem, as some people prefer the original format over unclean aggregated sources.  So I ask developers to start adding web archive sources for us, thanks.

**Website link:** `Sample of Completed novel url: `
https://web.archive.org/web/20161119214524/http://www.wuxiaworld.com/cdindex-html/

**Comment by Flameish** [comment]
I don't add new sources currently. You would have to try your luck with manual grabbing for now.
