### ISSUE TITLE
No cover image and metadata

### ISSUE THREAD

**Issue by zpereyra** [Flameish/Novel-Grabber#32]
Only tried it on dreame but the rendered epub is only titled as unknown.epub. Also, no cover and metadata. Option for get images was checked.

**Comment by Flameish** [comment]
Thanks for the report! I fixed it for Dreame & FicFun (they use the same page), check out 2.5.1. 

The option to get images only relates to images inside the chapter body so it doesn't need to be checked to get the cover. On a side note: downloading images doesn't always work when headless grabbing is used(for now). You can manually add the cover image in that case. Same goes for editing author/title and the other metadata when it shows as unknown. The program only really needs to have the chapters(chapter count) to work.

**Comment by zpereyra** [comment]
Thank you for the prompt response. I'll let you know if I see any other issues.
