### ISSUE TITLE
[SITE BROKEN] Chrysanthemum Garden

### ISSUE THREAD

**Issue by MylesC-cs** [Flameish/Novel-Grabber#329]
Chrysanthemum Garden
The site has implemented a password system on some novels, is there any way to have the grabber account for the password with a field?

**Comment by MylesC-cs** [comment]
Found a manual workaround

**Comment by Elthara** [comment]
Does your workaround still work? And would you be willing to share? I haven't had any luck since they changed the password system to require entering it again every chapter.
