### ISSUE TITLE
[FEATURE REQUEST] Multi-Thread + RLT text + a problem

### ISSUE THREAD

**Issue by 9ofe** [Flameish/Novel-Grabber#333]
Can you add multi thread? it takes a lot of time to download the chapters, for 1500 it takes like 30mins if it's multi threaded it would be much faster

and can you make the pdf conversion support right to left text, Font changer and font size. with these three it would be perfect
I had to make all these by myself..

plus in some websites the chapter container takes some times to appear (300-1000ms)
if I make it auto detect it picks a different 'box', and when I manually select it I get no output, however that get fixed when I use a browser (chrome/firefox)

also there is a problem, 
in whatever website the text is for example like this
" 
Hello 

Hello world

Github
"
when scraped it becomes
" 
Hello 
Hello world
Github
"

plus a lot of times what the text in the pre preview is like
"
Hello
e3c99b1
don't download
2h9asja
Hello world
ja012u
don't download
9012ia
"
but when I grab the chapters in txt file it becomes something like
"
Hello  e3c99b1  don't download
2h9asja
Hello world  ja012u
don't download
9012ia
'"
you get the idea, these whatever things are to protect the text, anyway they are pretty easy to remove with np++ but with the output is ruined like that it gets complicated.. very complicated. 

and thank you for this great tool.

**Comment by Flameish** [comment]
Sorry for the late reply.
Multi-Threading is not the problem why it takes so long, the main bottleneck of grabbing is the host server on the other side. If the server is slow to respond with the requested chapter then sending multiple requests will not help but make it even worse for the host server (I can seem like a DDoS attack).

I currently don't have time to work on NG so as a workaround for your PDF request you could export to EPUB and then use another, more sophisticated, program to convert and format the novel to your liking.

For the late loading container, try using the headless browser option (in manual grabbing), it uses a real browser to visit the page with better javascript (container loading etc.) coverage. Maybe that helps.

You can also blacklist certain HTML elements via css selectors which will be removed from the finished chapter to circumvent the protection.
