### ISSUE TITLE
[FEATURE REQUEST] Telegram Bot

### ISSUE THREAD

**Issue by asawakoyriego** [Flameish/Novel-Grabber#335]
Hi! I try to make my own novel-grabber bot to convert personally my desired books from dreame.com but failed to do so. Please help me how to make it easily since I'm a noob when it come to this. I badly want to convert my favorite story in epub format. I don’t  have a laptop or PC to run the program. Please help me!

**Comment by Flameish** [comment]
The Telegram Bot requires the software to run as a backend, so PC is needed. Someone mentioned that you can run Novel-Grabber in the cloud through via [Heroku](https://www.heroku.com/java) for example. I can't help you there through.

**Comment by damare01** [comment]
> Hi! I try to make my own novel-grabber bot to convert personally my desired books from dreame.com but failed to do so. Please help me how to make it easily since I'm a noob when it come to this. I badly want to convert my favorite story in epub format. I don’t have a laptop or PC to run the program. Please help me!
@asawakoyriego 
`Novel-Grabber` grabs chapter links on the website and `dreame` only indexed the 5 or more chapters not the whole book. You can only only access the whole chapters through there app, I think that it will be impossible to scrape **dreame**.

**Comment by Flameish** [comment]
Closing this as there's already an issue open concerning Dreame: #256
