### ISSUE TITLE
Foxteller and similar sites dont work

### ISSUE THREAD

**Issue by yuukiw** [Flameish/Novel-Grabber#34]
The main issue seems to be that the grabber doesnt allow for javascript since the epub only shows 
" Chapter loading... Retry Chapters cannot be loaded without javascript."

Any chance you can add a vutton to enable js or fix issues like this?

**Comment by Flameish** [comment]
That is already supported. You need to check "Use headless browser" when grabbing, this will visit the site with your chosen browser. For Foxteller I would suggest adding `span` and `.in-article` as blacklisted tags.

**Comment by yuukiw** [comment]
how exactly do i add blacklsited tags?

**Comment by Flameish** [comment]
![screenshot](https://i.imgur.com/tvrb29J.png)

**Comment by yuukiw** [comment]
ah i see. Thank you.

On a different note, any reason why you cant delete more then once chapter from the link box at a time now?

**Comment by Flameish** [comment]
I'm literally working on that right now, I noticed that when trying out Foxteller earlier. It worked previously and I'm a bit confused as to why it doesn't. For now you can click on the large "+" button and just remove the lines manually. (The names and links have to match up)

**Comment by yuukiw** [comment]
anyways thanks for your help and your nice programm.

Do you plan to add something like bookmarklist, where it saves the settings and links of series if you press a butoon?

**Comment by Flameish** [comment]
I was thinking about adding a library of sorts where you add a novel and it keeps the already downloaded chapters. You could also get notification when the novel updates, I had something like that previously but threw it out because it didn't really fit to this being a "pure" grabber.

**Comment by yuukiw** [comment]
hmm now it throws:

[INFO]Writing epub...
[INFO]Finished.
[ERROR]invalid session id
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-6RE6QCP', ip: '192.168.178.40', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.116, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: C:\Users\kwras\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:12561}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: b9937e782559807091e56ff318cf2e93

**Comment by Flameish** [comment]
Working on it. The EPUB should have been successfully created through.

**Comment by yuukiw** [comment]
you reason for not adding it.
While i would like to have it, it kinda clashes against the idea of a pure novel grabber.
