### ISSUE TITLE
Webnovel Chapter Container Not Found

### ISSUE THREAD

**Issue by JDcarmelo** [Flameish/Novel-Grabber#346]
can you please update webnovel? it always say [ERROR] Chapter container not found. I tried several novels and it always say this word when grabbing, tried without using an account still the same, and I also tried deleting novel grabber and redownloading it still no luck

![image](https://user-images.githubusercontent.com/57732601/164256218-bd0e59f1-df1e-47a5-8619-7ebd69a9b277.png)

**Comment by Flameish** [comment]
See #343
