### ISSUE TITLE
Add PDF file format

### ISSUE THREAD

**Issue by xx255q** [Flameish/Novel-Grabber#38]
Right now I believe the only option is EPUB but the software i use cant read that, only PDF. So can there be an option to change what the output file format is?

**Comment by Sanjana679** [comment]
There are relatively simple epub to pdf converters online that you can run the epub file through.

**Comment by Flameish** [comment]
Initial PDF support added. Images not working yet.

**Comment by xx255q** [comment]
Thank you for all your effort

**Comment by Flameish** [comment]
Closing this for now. Feel free to open new issues for feature requests concerning PDF.
