### ISSUE TITLE
Request for adding MTLNovel.

### ISSUE THREAD

**Issue by apaxc** [Flameish/Novel-Grabber#40]
The thing is, I have realized that not all mtl is equal. As the translation quality varies a lot when comparing sites. 

The site requested for adding to grabs.

https://www.mtlnovel.com/

Thank you.

**Comment by Flameish** [comment]
From what I can see, the chapter list will require headless to get but the chapter body can be done the normal way. Will be in 2.8.1

**Comment by apaxc** [comment]
Great!
Thanks.

**Comment by Flameish** [comment]
Check out 3.0.0
