### ISSUE TITLE
Volarenovels problem

### ISSUE THREAD

**Issue by kyukyu08** [Flameish/Novel-Grabber#44]
There's no problem with grabbing chapters and the "epub" is created according to the logs. But all files are like this 
![epub](https://user-images.githubusercontent.com/69593236/90135295-23d37d00-dd7b-11ea-8875-ab91673843df.PNG)
I tried other sites and there was no problem.

**Comment by Flameish** [comment]
Are the chapters being downloaded? Because it says the file is 0 KB large.
Or are you saying the "Translated by" is wrong? 
Sadly I cant quickly fix that without releasing a new build. As a workaround you could edit the title yourself  before grabbing or set the filename format as <title> which will not display the author.

**Comment by kyukyu08** [comment]
I can see the chapters being downloaded but when it's done it becomes like that. File extension is not epub and 0 kb.

**Comment by Flameish** [comment]
Do you still have the problem in [3.0.0](https://github.com/Flameish/Novel-Grabber/releases/tag/3.0.0) ?

**Comment by kyukyu08** [comment]
I tried just now and it's still the same with volarenovels.

**Comment by Flameish** [comment]
I can't replicate it myself, it works fine for me. Can you post the console log if anything note worthy is displayed?

**Comment by kyukyu08** [comment]
![log](https://user-images.githubusercontent.com/69593236/90342404-c3f60400-e010-11ea-911c-7715bb206a07.PNG)

still creates this file:
![file](https://user-images.githubusercontent.com/69593236/90342433-04ee1880-e011-11ea-9a46-6f7adaa6b8fe.PNG)

**Comment by Flameish** [comment]
Does the page counter go up?

**Comment by kyukyu08** [comment]
Yes, it goes up to 33 pages.

**Comment by Flameish** [comment]
If other sites work, can you try changing the author, title, cover etc and try again?

**Comment by kyukyu08** [comment]
It worked! Changed everything and finally got my epub. Thank you!

**Comment by Flameish** [comment]
Can you try out which of them caused it?

**Comment by kyukyu08** [comment]
I tried changing it one at a time and it only works when I change the author.

**Comment by Flameish** [comment]
Thanks. That's really helpful!

**Comment by kyukyu08** [comment]
Thank you too!

**Comment by Flameish** [comment]
Author string is no getting sanitized for file creation.
