### ISSUE TITLE
After update cant start program

### ISSUE THREAD

**Issue by xx255q** [Flameish/Novel-Grabber#46]
I tried updating the program but nothing happened so then i tried restarting my computer and even deleting that folder but the program never pops up now and in task manager is at 0% for the java task. when trying to start either the old or new version of the program the library program was recreated but nothing else

**Comment by Flameish** [comment]
I forgot to adjust a link to a live file which is needed on startup. I updated the jar file in the 3.0.0 release now. My apologizes.

**Comment by xx255q** [comment]
That seems to be have fixed the issue
