### ISSUE TITLE
program now keeps locking up

### ISSUE THREAD

**Issue by xx255q** [Flameish/Novel-Grabber#48]
twice now, at chapters 930 and 1037 for two different series the program with now freeze and your forced to to go into task manager to shut it down

**Comment by Flameish** [comment]
Please post the console log, I can't see what went wrong without it.

**Comment by xx255q** [comment]
can you explain where to go/ how to get log

**Comment by Flameish** [comment]
You need to start NG from cmd/powershell (windows) or terminal (linux) via `java -jar Novel-Grabber.jar`
