### ISSUE TITLE
Track series will no longer update without restarting program

### ISSUE THREAD

**Issue by xx255q** [Flameish/Novel-Grabber#54]
If i leave it on and it was originally on chapter 105 it wont move from that spot until i restart the program. When it is restarted it wont remember what it already downloaded and now will have 2 copies of older updates along with the new chapters

**Comment by Flameish** [comment]
What do you mean "it wont move from that spot"? Are you talking about the 'last chapter' number being not updated to the 'newest chapter' number?
I think what you're looking for it the option 'Update last chapter number'.

**Comment by xx255q** [comment]
What I am talking about is it just to automatically search for new chapters
and if one was found would download without any input. Now what happens is
it seems to no longer search and I have to restart the program for it to
find updates

**Comment by Flameish** [comment]
Please set the polling interval to something low and post the console log of at least one download try. Also post your settings for that novel.

**Comment by xx255q** [comment]
I have the download new chapters box already checked and threshold set to
1. The only other box checked is update last chapter number
