### ISSUE TITLE
saving svg as image

### ISSUE THREAD

**Issue by cloudynightowl** [Flameish/Novel-Grabber#56]
Seems like svg cannot be saved, was wondering if you could add support for saving svg images.

**Comment by Flameish** [comment]
Can you give me the link of one using svg inside the chapter?

**Comment by cloudynightowl** [comment]
Sorry, seems like i got the problem wrong. Using the "get images" options doesn't work for some sites in manual. Tried using novelupdates (automatic) too, though similarly the image files also failed to save. 

Link: 
https://chichilations.home.blog/golden-stage/

**Comment by cloudynightowl** [comment]
Right, there's another problem I encountered. Some chapters in CG use .tooltip-toggle to enter their footnotes. When i use novel grabber to parse these chapters, the footnote does not save. Was wondering how to save them.

**Comment by Flameish** [comment]
The tool-tips are loaded via javascript. There is no easy way to fetch them. Sorry

**Comment by cloudynightowl** [comment]
ahh i c, thanks anyways.

**Comment by Flameish** [comment]
After a lot of trying around I've noticed that the problem lays with the image host website which prevents the download. The svg image is actually a png too.

**Comment by cloudynightowl** [comment]
if it's only a few images i'm actually fine with downloading the images manually and adding it in the epub using calibre, though thanks for trying. Noticed the svg is also a png too, weird filename. I'll close this issue if there's nothing else?
