### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by urekmazinx** [Flameish/Novel-Grabber#57]
can you please  make the output in  txt /pdf / html  format  and make chapter as list like this 
chapter 1
chapter 2
chapter 3 
chapter 4
chapter 5
.
.
.
.
.etc...
🙏🙏🙏🙏

**Comment by Flameish** [comment]
I don't plan on adding any output formats right now (maybe PDF in the future). 
If you open the EPUB file with a ZIP program, you can find each HTML chapter file inside the OEBPS folder. 
For everything else you can use any converter tool.
