### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#65]
Hi! I would like to request a feature where we could still download chapters even if there is Cloudflare running for the website? I mean after doing the captcha etc. Thank you!

**Comment by Flameish** [comment]
Headless grabbing was used for this but it seems like Clouflare changed their bot detection for which I haven't found a way around yet.

**Comment by croooked01** [comment]
Is this why support for Comrademao has been removed?Otherwise when I use URL from novels there on latest version it says"[ERROR]Host not supported: grabber .sources.comrademao_com not found."

**Comment by Flameish** [comment]
Yes, the headless browser which was needed in the past for Mao gets stuck on the clouflare page so I removed the source file for for now.

**Comment by mp3096** [comment]
https://streamable.com/175yjz
it finally worked
step 1. visit website in your own chrome browser and let cloud flare check then visit novel page first and last.
step 2. leave chrome tab open and after that start novel grabber go to manual chapter to chapter .
step 3. enter 1st and last chapter link and also next selector
step 4. change wait time to 2000  and headless browser
step 5.  sucesss https://streamable.com/175yjz
Issues with this method 
: after 30 chapters or so it starts to slow down the loading website 
possible fix maybe? 
add another wait function after 30 novel chapter sleep time for 10 second then resume regular  task or waitime maybe this would work
Important: visit comrade mao first before botting and let cloud flare check sucess.
https://streamable.com/175yjz

**Comment by mp3096** [comment]
i tryed samething with getlink for wuxianworld.site but failed
https://streamable.com/jlh1du
getlink with headless browser is instant as you can see in this video maybe add 20 second wait minute function in there can help?

**Comment by Flameish** [comment]
I've added Comrademao back in on the auto tab since I didn't get a cloudflare check and managed to download chapters even without headless.

**Comment by croooked01** [comment]
> I've added Comrademao back in on the auto tab since I didn't get a cloudflare check and managed to download chapters even without headless.
> 
> I guess it depends on heavy server traffic if its active.

Comrademao has stopped working again.It may be because they changed their website layout.

**Comment by Flameish** [comment]
Can't even connect to the webpage. They're have server issues again. Will take a look later.
