### ISSUE TITLE
can't download with image error

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#67]
I tried to download from CG, but I can't seem to save [this](https://chrysanthemumgarden.com/novel-tl/birdcage/) particular novel because there's an image error. I also can't seem to edit novel metadata? It seems like headerless browser is automatically enabled for automatic download, particularly for NU...can there be an option to have it disabled? Editing the chapter order also cannot be saved (i.e. removing chapters, but it would revert to the original even after saving).

I would also like to ask if downloading multiple novels simultaneously (e.g. with 2 novelgrabber windows opened) but with the same save location won't be a problem? 

Thank you very much for the update!

**Comment by Flameish** [comment]
Thanks for the report! 
Fixed the empty cover bug/metadata not opening and chapter order not being saved.
Also added a new tab in the settings for source specific options, now you can set NU to use headless or static grabbing.

Starting NG multiple times and saving to the same directory is working just fine for me. It stores everything in buffer until the EPUB is written to file, so there are no possible temp directory conflicts.
