### ISSUE TITLE
Chapter no and name 

### ISSUE THREAD

**Issue by mp3096** [Flameish/Novel-Grabber#68]
in older version before every chapter there was chapter no and title for example
chapter 1 xxxxx
blah blah novel content
chapter 2 xxxxx
blah blah content
chapter 3 xxxxx
....
so on

but recently after new update chapter no and name between text is removed for example if i download same novel as above again it will show following

blah blah novel content
blah blah content
....
so on

can u add chapter no and title back between or an option.
Thank you.

**Comment by Flameish** [comment]
Chapter numbering was never part of NG, tt will just take how it's on the website.
I might have adjusted the selector for that specific site and it's not picking up the "Chapter #" before title anymore through. Same goes for chapter name headlines before the chapter body but there is an option to manually add the chapter title to each chapter already. 

Also if you could link the novel/host, that would be great!

**Comment by mp3096** [comment]
Mtlnovel it happens not sure about other one

**Comment by Flameish** [comment]
![image](https://user-images.githubusercontent.com/47372220/99577620-ea468980-29db-11eb-8640-a7af52590b40.png)

With "Add chapter title" selected
![image](https://user-images.githubusercontent.com/47372220/99577649-f29ec480-29db-11eb-84df-7b778ffdd50a.png)

Looks fine to me?

**Comment by mp3096** [comment]
here is my setting
https://prnt.sc/vlsisg

not showing up for me
https://prnt.sc/vlsifu

**Comment by Flameish** [comment]
Okay I see it now, at least one bug. It shouldn't be in the <head>
![image](https://user-images.githubusercontent.com/47372220/99602338-951d6e80-2a01-11eb-875e-b9f78ca044fc.png)

**Comment by mp3096** [comment]
Works fine now thank you /close
