### ISSUE TITLE
Epub broken on Adobe digital editions and Kobo e-reader

### ISSUE THREAD

**Issue by ThaFartKnight** [Flameish/Novel-Grabber#69]
The exported epub file of the manual grabber doesn't work in adobe digital editions and on my kobo e-reader.
I got it working again when I replaced the 4 first lines in the chapter html files.
Before: 
```
<!--?xml version="1.0" encoding="utf-8"?--> 
<title></title>
<html>
 <head></head>
```

After: 
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
</head>
```

This seems to get it working again.

**Comment by Flameish** [comment]
Thanks for the report! I've switched some things around, please use the updater and try again.
