### ISSUE TITLE
Tooltips on CG and other Wordpress sites

### ISSUE THREAD

**Issue by lunevale** [Flameish/Novel-Grabber#70]
CG and some Wordpress sites make use of tooltips instead of regular/linked footnotes and NG can't grab these tooltips, which sometimes leads to loss of information. Could there be a solution for this?

**Comment by Flameish** [comment]
Can you link an example?

**Comment by lunevale** [comment]
From CG: https://chrysanthemumgarden.com/novel-tl/n1pb/n1pb-1/ the tooltip is underlined.
From a Wordpress site: https://perpetualdaydreams.com/novel/tyqhm/tyqhm-1/ the tooltip has a dotted underline.

**Comment by Flameish** [comment]
Each site of the supported ones is unique so I can't do a general work-for-all solution for all WP sites. Knowing WP, it's probably some kind of tool-tip addon/plugin anyway so there could be different ones as well. So until the site is supported it's a no for WP sites. You can always request a site to be added to the supported ones through (Needs to have 10+ novels on it)

**Comment by lunevale** [comment]
Ok that's understandable, thank you. What about the ones on CG though?

**Comment by Flameish** [comment]
I tried my best but I can't quite figure out where the tool-tip text comes from. They're being fetched on click which makes this not that easy. Sorry

**Comment by lunevale** [comment]
I see. Thanks so much for your help.
