### ISSUE TITLE
Wuxiaworld.site note working?[Solved]/Other miscellaneous issues

### ISSUE THREAD

**Issue by TehGodofDoooom** [Flameish/Novel-Grabber#71]
Hey!
I'm a user of your novel grabber and it's REALLY made my day, especially when my internet cuts out. I just wanted to mention that wuxiaworld.site links don't seem to work, it just says "HTTP error fetching URL" anytime I try to use a wuxiaworld.site link. 
Thanks

**Comment by Flameish** [comment]
Seems like they're using Cloudflare during heavy traffic as well. Same problem as #65. Can't really do anything until I find a workaround.

**Comment by TehGodofDoooom** [comment]
understood, also I have another problem.. I was downloading a novel from scribblhub and the recent chapters weren't fully 'acquired' per say. Simply put theres a lot of text missing, is it because it's in italics? I tried using remove styling as well but it didn't change anything, parts of the chapter(s) were still missing, for the record the novel I'm referring to is this one: 

https://www.scribblehub.com/series/10957/the-simulacrum/

the most recent few chapters(63 part 1,2 and 3) are missing some of the dialogue, presumably because it was in a different format or something(Idk I'm a noob here) would appreciate a solution here.
Also for the record, here is an image comparison from chapter 62 part 1,

Epub:
![image](https://user-images.githubusercontent.com/74888231/100178735-8a9c2280-2ea2-11eb-808a-d2fae301ea65.png)

From ScribblHub:
![image](https://user-images.githubusercontent.com/74888231/100178924-f2526d80-2ea2-11eb-9784-0dd23ac798f4.png)

Thanks.

**Comment by Flameish** [comment]
"Remove styling" only removes the style attribute from HTML elements so it won't help in this case since the symbols to annotate the dialog (`<` and `>`) are the problem. The HTML cleaner sees them as broken HTML elements and deletes them. I will try to think of a solution or work around.


Can you elaborate on your scrolling problem a bit more? The Calibre E-Book Viewer works like it's supposed to for me, maybe I misunderstood you through:
![Peek 2020-11-25 12-30](https://user-images.githubusercontent.com/47372220/100222830-f326e600-2f1a-11eb-8d84-1d7117ad9208.gif)

**Comment by TehGodofDoooom** [comment]
I see, I hope you can come up with a workaround for the annotated text. Regarding the scroll, in the previous version of Novel grabber(prior to version 3) the epub files were segregated into pages and could be flipped through using right and left(arrow keys) now it has somehow made the entire chapter as a page, so I can't flip through it like a book, but have to scroll down kind of like how you read webnovels on Qidian(webnovel.com) that infinite scroll type format. After checking this appears to be a Calibre problem but it was perfectly fine before I used version 3 to make an epub file, thus I'm a little confused and if there is a setting in Calibre that would allow me to use my arrow keys to flip pages I would appreciate some help.

**Comment by Flameish** [comment]
Closed in favour of #73
