### ISSUE TITLE
New Site Requests

### ISSUE THREAD

**Issue by Flameish** [Flameish/Novel-Grabber#72]
New site requests go here!

Rules for new sites to be added:
- Needs to host at least 10 novels

**Comment by mp3096** [comment]
https://novelsrock.com/
https://boxnovel.net/
https://lnmtl.com/

**Comment by Flameish** [comment]
All added!

**Comment by TehGodofDoooom** [comment]
https://www.wuxiaworld.co/
https://www.readlightnovel.org

also for sites that have been added can you update the main page?  Since you removed the site selector it's kinda confusing to figure out which sites can be pulled from

**Comment by Flameish** [comment]
They're still on the main page, just a bit further down!

**Comment by Flameish** [comment]
Added both sites!

**Comment by RipDeamon** [comment]
https://f-w-o.com/

**Comment by Flameish** [comment]
I'm not really digging that site. For one, there are only 18 novels total and half of them are VIP only.

**Comment by JasCU100** [comment]
Can you please add support for http://www.tapread.com? Thank you!

**Comment by Flameish** [comment]
TapRead is [already](https://github.com/Flameish/Novel-Grabber#natively-supported-sites) supported!

**Comment by mp3096** [comment]
u added https://lnmtl.com/  but chapter #'s are not coming in between.
its just continuous text.

**Comment by roshavagarga** [comment]
https://veratales.com/
https://readnovelfull.com/
https://boxnovel.org/
https://vipnovel.com/
https://www.asianhobbyist.com/
https://moodylit.com/ - doesn't cover the requirement for 10 novels, but I'd argue for an exception, original content.

**Comment by Flameish** [comment]
Is there a difference between [novelfull.com](https://readnovelfull.com/) (already supported), [readnovelfull.com](https://readnovelfull.com/) and [boxnovel.org](https://boxnovel.org/)? Looking at the new release feed they all seem pretty much identical.

Will add all the others through! Also gonna take a look at lnmtl.

**Comment by roshavagarga** [comment]
@Flameish Mild differences as far as when something gets uploaded, they're probably the same as far as 'innards' go. Vipnovel is also sort of ther same, though that one's closer to the other boxnovel websites. All in all, they're all crawler-like websites that sometimes have varying differences as far as what gets crawled and how often.

**Comment by Flameish** [comment]
Sorry for the delay.
@roshavagarga I've added all sites except moodylit as all novels hosted on there are also on Royal Road.
@mp3096 Can you elaborate a bit more? Maybe with examples/links, since I can't see what is supposedly wrong.

**Comment by mp3096** [comment]
> Sorry for the delay.
> @roshavagarga I've added all sites except moodylit as all novels hosted on there are also on Royal Road.
> @mp3096 Can you elaborate a bit more? Maybe with examples/links, since I can't see what is supposedly wrong.

https://lnmtl.com/novel/detective-from-the-future
try use this novel and check output u can see there is 
blah blah 
blah blah
but it should suppose to be
blah blah 
chapter 2
blah blah
also there table of content is messed up
with this
Table of Contents
In the future police
Studies Tyrant
Suspects
New skill
Micro-Expression Analysis

**Comment by Flameish** [comment]
So you want to have chapter numbers in front of the chapter names and the chapter title at the start of each chapter? For the latter there is the option to have it added to each chapter.

**Comment by azurymous24** [comment]
Hi! Is it possible to add these translator's sites?

https://kktranslates.home.blog
https://snowycodex.com
https://untamedalley.com
https://blackbox-tl.com
https://dummynovels.com
https://exiledrebelsscanlations.com/novels/

**Comment by lunevale** [comment]
Could you please add https://www.chickengege.org/ ?

**Comment by mp3096** [comment]
add this 
https://jpmtl.com/

**Comment by apaxc** [comment]
Site request 

https://fastnovel.net/

Thanks

**Comment by asmodea** [comment]
Site request:

http://www.jjwxc.net/

**Comment by TehGodofDoooom** [comment]
daonovel.com, appears to be a wuxiaworld.site clone or something, a lot of wuxiaworld links go there.

**Comment by RipDeamon** [comment]
Site request:
https://www.novelupdates.cc

**Comment by RipDeamon** [comment]
Site request:
https://fastnovel.net

**Comment by lunevale** [comment]
Hi could you please add these chinese sites as well?
https://www.zhenhunxiaoshuo.com
https://shubaow.net

**Comment by Flameish** [comment]
Added all sites except [https://kktranslates.home.blog](https://kktranslates.home.blog) (Not uniform and too few novels)

I need some feedback on the new chinese sites if everything is correct. ([shubaow.net](https://shubaow.net), [zhenhunxiaoshuo.com](https://www.zhenhunxiaoshuo.com), [jjwxc.net](http://www.jjwxc.net/))

I'd also like to remind everyone about manual grabbing which was made for these small translator sites. These wordpress sites are really awful to scrape nicely.

**Comment by asmodea** [comment]
Oh, woot jjwxc is working now! but is it possible to add login for it? Otherwise it only gets the non-VIP chapters.... On the homepage the selectors for the login inputs are 
username: `#logininput input[name="loginname"`
password: `#logininput input[name="loginpassword"]

But there's also a captcha as well with the login (the input field is `#login_auth_num input[name="auth_num"]`, the image is `#login_auth_num img`

Also I notice that when the title/author is Chinese, it shows up as boxes in the interface (but it turns out just fine in the final epub, so it's not really a big issue).
![Screenshot_1](https://user-images.githubusercontent.com/3158158/103337289-ab224400-4a2f-11eb-9898-fba9f9b3ba56.png)

**Comment by Flameish** [comment]
No promises with login that use captcha for now. I need to actually rework that system.
The missing chinese seems to be a font thing, I'll take look. Just curious that nobody else reported that problem till now.

**Comment by lunevale** [comment]
Thank you so much for adding the sites! Shubaow and zhenhunxiaoshuo work well on on pc but regarding the telegram bot, it only works with shubaow.

**Comment by Flameish** [comment]
Can you elaborate a bit more in regards to zhen? The bot is just a different interface for NG, the back end is one and the same. If it works on PC it should work with the telegram bot as well.

**Comment by soujanyabukka** [comment]
Add sofanovel.com

**Comment by lunevale** [comment]
> Can you elaborate a bit more in regards to zhen?
Oops my apologies. Zhenhun works on the telegram bot, but not shubaow. I just get the message that the bot can't download the novel.
![IMG_20201231_122907](https://user-images.githubusercontent.com/73226124/103394515-e9b91b00-4b63-11eb-8701-6e01be2cc325.jpg)

**Comment by Flameish** [comment]
When I try to visit that site in my browser I get:
`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

**Comment by JasCU100** [comment]
Can you please add:
https://fujossy.jp/ 
https://mnlt.syosetu.com/

It would be great if it could scrape all the chapters in fujossy even if the table of contents has multiple pages. Thank you!

**Comment by yuukiw** [comment]
https://bigclosetr.us/ would be nice to have

**Comment by lunevale** [comment]
> `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

I just checked on my pc and the site is up and running so I'm not sure what the problem is. No worries though, I'll just use the jar file when I want to download something from shubaow since it works there. Thanks again.

**Comment by Flameish** [comment]
Why is that URL different from the normal ones? When I check others, the TOC is always at shubaow.net/11_1111/  e.g:
[https://www.shubaow.net/14_14162/](https://www.shubaow.net/14_14162/)
[https://www.shubaow.net/22_22735/](https://www.shubaow.net/22_22735/)
[https://www.shubaow.net/3_3167/](https://www.shubaow.net/3_3167/)

**Comment by jumiss** [comment]
Can you please add support for https://webtruyen.com/ and https://truyenfull.vn/ Thank you!

**Comment by HarmonLucifer** [comment]
https://9kqw.com/

http://book.qq.com/

http://wenxue.iqiyi.com/

http://www.biquge.se/

https://www.17k.com/

https://www.101novel.com/

Thanks!

**Comment by lunevale** [comment]
> Why is that URL different from the normal ones? When I check others, the TOC is always at shubaow.net/11_1111/ e.g:
> https://www.shubaow.net/14_14162/
> https://www.shubaow.net/22_22735/
> https://www.shubaow.net/3_3167/

Hey those links work on the telegram bot! I'm not sure why the link to the book I wanted is different but thanks for informing me why the download failed.

**Comment by HarmonLucifer** [comment]
Are you gonna add them any time soon?

**Comment by Flameish** [comment]
I add sites when I feel like it. Each new one can take from 15 minutes to multiple hours. I've already added [https://fujossy.jp/](https://fujossy.jp/), [https://webtruyen.com/](https://webtruyen.com/) and [https://truyenfull.vn/](https://truyenfull.vn/) a few days ago. I also have to maintain the already added sites(60+). This is still my own _hobby_ project and I won't let myself be rushed.

**Comment by HarmonLucifer** [comment]
Well, take your time I'm just checking

**Comment by croooked01** [comment]
Site request:
https://novelfun.net/

**Comment by Flameish** [comment]
Added all sites except:
- syosetu.com and bigclosetr.us as both have a download/pdf/printer option on their sites
- http://book.qq.com/ possible encryption of chapter content?

Sofanovel still needs a bit of work and will be released at a later date.
NovelFun is pretty buggy but works.

**Comment by Flameish** [comment]
Sofanovel.com has been added.

**Comment by Tetdesu** [comment]
https://novelsonline.net/

**Comment by soujanyabukka** [comment]
Please upload Booknet.Com also. In telegram i cannot download dreame and
sofanovel stories can u please check it. It is saying enter valid url

**Comment by JasCU100** [comment]
Can you also please add https://www.alphapolis.co.jp/novel/ ? Thank you very much!

**Comment by PleaseReadMe** [comment]
https://www.machine-translation.org/
https://comrademao.com/

**Comment by PleaseReadMe** [comment]
https://www.machine-translation.org/

**Comment by Flameish** [comment]
Added all sites.
AlphaPolis requires headless grabbing for now and booknet.com has an inbuilt wait of 2-5 seconds per chapter. If they still block you (Http error 429) you can try and set the wait time higher.

**Comment by Flameish** [comment]
@soujanyabukka I don't have any problems with sofanovel. Please open a new issue and paste the URL you're trying to enter.

**Comment by 1jamie7** [comment]
https://www.novicetranslations.com

thank you ❤

**Comment by Flameish** [comment]
Too few novels (min 10 and I really don't like WordPress sites). Try using manual grabbing.

**Comment by PleaseReadMe** [comment]
https://ontimestory.eu

**Comment by PleaseReadMe** [comment]
Manual grabbing on telegram

**Comment by Flameish** [comment]
I'm closing this thread. It's getting too long and often off topic. Please open a new site request issue for new sites from now on.
@PleaseReadMe Please open a new feature request issue with your ideas since I don't have one for now.
