### ISSUE TITLE
'<' and '>' getting removed inside text

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#73]
I've noticed missing text when a word starts with "<" like [here](https://chrysanthemumgarden.com/novel-tl/surprise/surprise-79/). It should be "The hypothesis quotes a line from the Red Queen in <Alice>." but the epub only contains "The hypothesis quotes a line from the Red Queen in ." Thank you!

**Comment by Flameish** [comment]
As mentioned in #71, this is a problem coming from the HTML cleaner which sees them as broken elements and removes them. Working on a solution.

**Comment by Flameish** [comment]
Update and try again. It should display them correctly now.

**Comment by JasCU100** [comment]
Thank you very much!

**Comment by TehGodofDoooom** [comment]
Does it work properly now?
