### ISSUE TITLE
headless browser for mac os/chrome error

### ISSUE THREAD

**Issue by avramirez** [Flameish/Novel-Grabber#74]
This tool is awesome. 

Basically what I'm trying to do is use it with webnovel site. 
When using auto grab , it doesn't detect that I'm logged in. (That means locked chapters can't be scrapped)
And account is not supported for webnovel llinks.

So I thought of using headless browser. But I get this error:
```
[HEADLESS]Starting browser...
[ERROR]invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: profile.managed_default_content_settings.images
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MacBook-Pro.local', ip: '<REDACTED I REMOVED THE VALUE>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '14.0.1'
Driver info: driver.version: Driver
remote stacktrace: 0   chromedriver                        0x0000000104a2ac29 chromedriver + 2464809
1   chromedriver                        0x00000001050656f3 chromedriver + 8996595
2   chromedriver                        0x000000010486fd56 chromedriver + 650582
3   chromedriver                        0x00000001047dd5a1 chromedriver + 50593
4   chromedriver                        0x00000001047e0cb5 chromedriver + 64693
5   chromedriver                        0x00000001047d9494 chromedriver + 33940
6   chromedriver                        0x00000001048144f6 chromedriver + 275702
7   chromedriver                        0x0000000104813d78 chromedriver + 273784
8   chromedriver                        0x000000010481519d chromedriver + 278941
9   chromedriver                        0x00000001048123f3 chromedriver + 267251
10  chromedriver                        0x00000001047ec230 chromedriver + 111152
11  chromedriver                        0x00000001047ed1a7 chromedriver + 115111
12  chromedriver                        0x00000001049fd830 chromedriver + 2279472
13  chromedriver                        0x0000000104a0883a chromedriver + 2324538
14  chromedriver                        0x0000000104a084a7 chromedriver + 2323623
15  chromedriver                        0x00000001049e4945 chromedriver + 2177349
16  chromedriver                        0x0000000104a08d41 chromedriver + 2325825
17  chromedriver                        0x00000001049f2bda chromedriver + 2235354
18  chromedriver                        0x0000000104a1dc4a chromedriver + 2411594
19  chromedriver                        0x0000000104a2f987 chromedriver + 2484615
20  libsystem_pthread.dylib             0x00007fff72fbe109 _pthread_start + 148
21  libsystem_pthread.dylib             0x00007fff72fb9b8b thread_start + 15
```

I guess mac os support is not available for headless browser? 

------

**This is unrelated, but just a suggestion.**
I tried to check the payload that webnovel used. They are asking 
in header
```
cookie
```
in  parameters
```
_csrfToken
```
Maybe we can add option to just add them manually? 
Or put it in the accounts list. Instead of username and password. Provide csrfToken value?
 And attach them to the autoscrapper request?

**Comment by Flameish** [comment]
For your first problem: Check if your chrome up-to-date. I'm passing a few arguments to chrome (eg. not to load images to improve speed) and I think some are not supported in your/mac version.

The problem with webnovel is that they have 2 step authentication which makes the current method (just sending a POST request and fetching the cookies) not possible. 

Also thanks for your suggestions! I will add the option to set cookies for manual grabbing and see what I can do to improve auto login. Maybe opening a browser window to login and then save the cookies should be uniform and easy to use for all sites.

**Comment by avramirez** [comment]
Thanks for the quick reply. I tried to update it to latest chrome. Still fails for headless browser option.

Oh well. Again, Thanks for this super useful tool. I'm able to download most of the novels that I'm planning to read and have read. 

The webnovel thing sucks. I mean we paid for the locked/paid chapters but we never get to own it or download it. It is like buying a book but you could never get your own copy.

Closing this ticket now. Thanks again
