### ISSUE TITLE
running the application.

### ISSUE THREAD

**Issue by bap269** [Flameish/Novel-Grabber#75]
HI I cant seem to find the launcher? what is its file name and extension?

**Comment by Flameish** [comment]
NG-Launcher.jar is inside the extracted zip.

**Comment by bap269** [comment]
I cant find it. How do I execute the terminal commands?

**Comment by Flameish** [comment]
I'm pretty confused of what you're trying to say.
If you just want to run Novel-Grabber you can [download](https://github.com/Flameish/Novel-Grabber/releases/latest/download/Novel-Grabber.zip) the zip and extract it. If you're on windows you can just execute the NG-Launcher.jar inside the folder like any other exe. (You need to have Java 8+ installed) Starting the program via terminal commands just gives you better error reporting.

Or what are you trying to do?

**Comment by bap269** [comment]
Oh I'm sorry what I'm trying to say is there's no file called NG-Launcher.jar when I extracted the Novel Grabber I downloaded here. I already have a Java 8+ installed.
![Screenshot (9)](https://user-images.githubusercontent.com/54578953/101715672-da036500-3ad6-11eb-9be8-96fd6b2028ff.png)

**Comment by bap269** [comment]
oh sorry soryy... found it already. sorry for the incovenience..
