### ISSUE TITLE
[Feature request]: Automated download from queue

### ISSUE THREAD

**Issue by roshavagarga** [Flameish/Novel-Grabber#76]
I'm probably not wording this ideally, but here's what I'd like:
1. Saving 20+ URLs in a list somewhere.
2. Making Novel-Grabber make a simple check of said URLs - getting the info in a simple list (last chapter, cover availability, etc.)
3. Being able to choose which of these to download.

Basically I have a list of novels I like reading and I sometimes update them - doing it 1 by 1 is tedious, especially since NG takes a while to handle bigger novels. A good example is `Reincarnation of the strongest sword god` - takes 15+ minutes, if not more, to get it from boxnovel.

Bonus feature: Having the ability to search for sources within NG, though that might warrant a separate issue.

**Comment by Flameish** [comment]
A bit confused about 3). What exactly do you mean with "choosing which to download"? 
Also what do you mean with "update" the novels? Do you mean the full novel or just the last few not-read chapters, because you could use the library function for that part.

Already thought about a lookup/search function which checks all sources for the novel. Just not sure how I'm going to do it.

**Comment by roshavagarga** [comment]
I'm basically redownloading and creating new epubs every time and replacing them with on top of old ones in my ebook reader.

As far as 3, some novels might have a big hiatus at times or be dropped since the last time I checked. I did notice library, but as far as I can see, it creates new epubs with the missing chapters since last check, rather than a whole new epub containing everything or combining the previous epub with the latest chapters?

**Comment by Flameish** [comment]
You're correct, it was intended to get/follow the last unread chapters. But you can use it for your case with a bit of tinkering as well:
- Add all your novels to the library and make sure that the option "update last chapter" is turned off
- Edit the `library.json` file with a text editor and change every value of the parameter "lastChapter" to 1
![image](https://i.imgur.com/zkU1c8F.png)
- After restarting NG you can just download them from the library

(I've just noticed a bug where it visually updates the last chapter number to the newest but after restarting NG the counters are back at 1)

**Comment by Flameish** [comment]
To download from a queue you can easily use the CLI and build a script around that. [Example](https://superuser.com/questions/1331746/batch-command-script-to-do-commands-from-txt-file)
