### ISSUE TITLE
How to run the JAR

### ISSUE THREAD

**Issue by DevilzPride** [Flameish/Novel-Grabber#78]
how to use should be more specific for newbies they don't know how to use this properly even though I have installed Java I'm still having problems 
![Screenshot of Novel Grabber](https://user-images.githubusercontent.com/75960236/102102507-cd0eaa80-3e23-11eb-97f5-009dcb7b3115.png)
launching

**Comment by Flameish** [comment]
1) Just double click. Might work if jars are already associated with Java
2) Right click jar -> Open with -> Java
3) Shift-right click somewhere inside the folder -> Open Power Shell here -> `java -jar NG-Launcher.jar`

**Comment by DevilzPride** [comment]
> 1. Just double click. Might work if jars are already associated with Java
> 2. Right click jar -> Open with -> Java
> 3. Shift-right click somewhere inside the folder -> Open Power Shell here -> `java -jar NG-Launcher.jar`

thanks doing the third step helped

**Comment by Flameish** [comment]
If you don't want to run the patcher every time (updates are frequent through), you can go inside the bin folder and do the same for the Novel-Grabber.jar

**Comment by DevilzPride** [comment]
Is it possible for me to grab more than 55 chapters because I want to read a light novel to the latest chapters without paying for it

**Comment by Flameish** [comment]
You did not mention from which website you're trying to grab from but NG is not and will not support VIP/paid chapter download without login/user account. A few aggregator sites are support through, take a look at the [supported hosts](https://github.com/Flameish/Novel-Grabber#natively-supported-sites).

**Comment by DDC1234** [comment]
I can't get it open.
I get to the point where it says select browser but nothing is opening.
I also can't get the -gui and -help to work? 
Win 8.1 64bit java 8 just downloaded it today

**Comment by Flameish** [comment]
Can you try to start the Novel-Grabber.jar inside the bin folder and post the console log? The CLI arguments are also only working if you start the main Novel-Grabber.jar. 
`-gui` is the same as giving it no arguments

**Comment by botze90** [comment]
> You did not mention which website you're trying to grab from but NG can not and will not support VIP/paid chapter download without login/user account. A few aggregator sites are support through, take a look at the [supported hosts](https://github.com/Flameish/Novel-Grabber#natively-supported-sites).

Hello, can you show me a way to use login/useraccount for webnovel ?
Only found booklat and wuxiaworld in GUI

**Comment by Flameish** [comment]
Login on Webnovel is now possible again. As should any other host.

**Comment by Saadsem** [comment]
I downloaded Java and still doesn't want to open
