### ISSUE TITLE
Can't download from Scribblehub

### ISSUE THREAD

**Issue by dando20** [Flameish/Novel-Grabber#79]
I tried to use this program to download a story from Scrubblehub, but I keep getting 

[ERROR]Could not connect to webpage. (HTTP error fetching URL)

Any idea what is happening?

**Comment by Flameish** [comment]
Are you using the correct URL? ex: `https://www.scribblehub.com/series/204714/salvos/`
If it's still not working please start Novel-Grabber.jar inside the bin folder from the terminal / PowerShell and paste the console output:
(Shift-right click somewhere inside the folder -> Open Power Shell here -> `java -jar Novel-Grabber.jar`)

**Comment by dando20** [comment]
I used your example and it still didn't work.
and bin folder? SOrry I'm new to all of this.

**Comment by dando20** [comment]
Wait never mind. It seems my VPN was blocking it somehow. So turning it off (temporarily) seems to do the trick
