### ISSUE TITLE
Regarding DREAME

### ISSUE THREAD

**Issue by GorgeousMhica** [Flameish/Novel-Grabber#83]
Hi, I would like to report that when I tried to download dreame stories, it only download the description of the story, but the story content itself is plainly blank. I both tried telegram bot as well as the app but it's just the same. I hope that you can check this and fix it. Thank you for your effort. Have a nice day.

**Comment by Flameish** [comment]
Thank you very much for the report! Fixed chapter text and cover image.
Also the app and the bot are one and the same, if one doesn't work the other wont either.

**Comment by GorgeousMhica** [comment]
Wow, thank you so much for fast response. Godbless you and stay safe.
