### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by azurymous24** [Flameish/Novel-Grabber#85]
Hi! Just wanna ask, will it be possible to create epub even though the chapters are in google docs? I tried downloading in novel updates but unfortunately the chapters were all uploaded in google docs so the novel grabber didn't read it. It created an epub but there's no chapter text on it.

Here's the example.

Title: Are you Ok
Reader: Lithium
Source: novelupdate

![Screenshot_2020-12-22-09-09-43-93_528fcc6268b5cf6bef0c8d3ef9270e11.jpg](https://user-images.githubusercontent.com/73337125/102836925-7ff48080-43af-11eb-9f7d-96b67059c872.jpg)
![Screenshot_2020-12-22-09-09-38-96_528fcc6268b5cf6bef0c8d3ef9270e11.jpg](https://user-images.githubusercontent.com/73337125/102836933-8551cb00-43af-11eb-8f7b-b7c00e650ea0.jpg)

**Comment by Flameish** [comment]
Last time I tried it wasn't possible. Also each of these are private anyway I think?

**Comment by azurymous24** [comment]
Oh, okay. Thanks for the heads up!
