### ISSUE TITLE
Add Safari Support

### ISSUE THREAD

**Issue by RandomDSdevel** [Flameish/Novel-Grabber#86]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Safari isn't currently a browser Novel-Grabber supports using; please add it.  (Actually, didn't an older version of the software not require an external browser at all…?)

**Comment by Flameish** [comment]
The browser selection does not matter at all if you don't use (headless)browser grabbing. I don't think a single automatic/supported uses it.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Great, thanks!  That setting needs some help description text, though; it's not obvious what it does…
