### ISSUE TITLE
#Request for Help

### ISSUE THREAD

**Issue by Raeyraey** [Flameish/Novel-Grabber#88]
Good day! First of all, thank you so much for making this wonderful thing! It really helps me to read my favorite novels. Second, it amazes me how efficient and effective it is so a big thumbs up y'all. By the way, I just discovered it yesterday and so at the moment I am having a problem with stopping the queue download. I am a new user of your telegram bot and I really want to know if there's such a thing as cancelling the ongoing download. I have waited for almost an hour to one of my ongoing download and it really wasn't moving at all. Thank you and keep up the good work!

**Comment by Flameish** [comment]
Thanks for the feedback!
I've added a /stop command which will cancel an ongoing download.

**Comment by Raeyraey** [comment]
Thank you so much!
