### ISSUE TITLE
Errors not indicated

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#90]
Hello! I noticed that whenever there are errors lately, there doesn't seem to be any indicators at the end after finishing the creation of epub? Thanks!

**Comment by Flameish** [comment]
I redid the info/error output recently and used a lot of search-and-replace to do this so there are probably a lot of mistakes like this, thanks for reporting. Having said this, I'm not quite sure what kind of errors after finishing you are referring to. The only error or reports which gets printed after the EPUB should be failed chapters.

**Comment by JasCU100** [comment]
Oh some errors I get is chapter container not found. Before it would indicate at the end that the chapter is not downloaded.

**Comment by Flameish** [comment]
Check out the new update and tell me what you think!

**Comment by JasCU100** [comment]
> Check out the new update and tell me what you think!

Wow, it's a really good improvement! :) We could download failed chapters without downloading from the beginning! Thank you very much!
