### ISSUE TITLE
Wuxiaworld.site not working

### ISSUE THREAD

**Issue by TehGodofDoooom** [Flameish/Novel-Grabber#91]
Tried using wuxiaworld.site Links recently and it just isn't loading, just get an infinite loading circle.
![image](https://user-images.githubusercontent.com/74888231/106231922-cb752800-61c0-11eb-83db-d56ee961afd1.png)

The image above was when I tried using a wuxiaworld link after succesfully downloading something else from scribblhub.

**Comment by Flameish** [comment]
Thanks for the report!
It seems the title selection had changed, so it got stuck. Should be fixed now.
