### ISSUE TITLE
Request for Help

### ISSUE THREAD

**Issue by Raeyraey** [Flameish/Novel-Grabber#96]
Hello! I am just here to ask if there's something I need to do to download a story from Dreame? I mean I can download any stories from other sites included, it's all fine but it seems that Dreame doesn't work on the telegram bot. I tried the link both from the site and app but it's really not working. It always says it's not supported. I hope you can help me and it's not too bothersome. Thank you for the hardwork!

**Comment by Flameish** [comment]
Dreame doesn't work on the telegram bot since it requires an account. I always forget to remove Dreame from the bot sources.

**Comment by Raeyraey** [comment]
Oh, is that so? then it can't be helped. But thank you for your quick response!

**Comment by Flameish** [comment]
You could use the desktop version and enter your own account for now. Alternatively you could run your own bot. Just ask if you have any questions!

**Comment by Raeyraey** [comment]
That's a great help! Thank you so much, I'll try that then. And really, many thanks in making this one. 😊
