### ISSUE TITLE
Booknet is not working in bot

### ISSUE THREAD

**Issue by soujanyabukka** [Flameish/Novel-Grabber#97]
I have tried so many times but it is not working
![Screenshot_20210204-212753](https://user-images.githubusercontent.com/31979580/106919755-6f665280-6730-11eb-9b57-e0a72bb7495c.png)

**Comment by Flameish** [comment]
Booknet got a pretty strict limit of request per seconds/minute. Try increasing the wait time between each chapter and see if it still fails at the same point:
`-link https://booknet.com/en/book/his-doll-b260737 -wait 3000 -getImages`

**Comment by Flameish** [comment]
Ah! Found the culprit. If you check the first chapter, you will see a mature warning and you need to be logged to view it.
