### ISSUE TITLE
[SITE REQUEST] https://www.lightnovelworld.com/

### ISSUE THREAD

**Issue by Mkjafu** [Flameish/Novel-Grabber#98]
**Does the host have more than 15 novels?**

Yes

**Did you try manual grabbing?**

Yes, but it failed.

**Website link:**
https://www.lightnovelworld.com/

**Comment by Flameish** [comment]
Added.

**Comment by Flameish** [comment]
Also, manual grabbing works perfectly fine. I made a little video showcasing how to do it for sites which use pagination on the table of content page. Might help you in the future:

https://user-images.githubusercontent.com/47372220/106944115-81db8e80-6726-11eb-89a2-d67b277f5cc9.mp4
