### ISSUE TITLE
[BUG] Cant grab from Asian Hobbyist using the Telegram Bot

### ISSUE THREAD

**Issue by Tetdesu** [Flameish/Novel-Grabber#99]
Cant grab from Asian Hobbyist using the Telegram Bot

I tried using the telegram bot to grab from Asian Hobbyist but it didnt work.

![Screenshot_20210206_083835_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/75838212/107105378-edc21200-6860-11eb-8539-4d4b3886abff.jpg)

**Platform**
Telegram Bot

**Comment by Flameish** [comment]
Fixed.
